### ISSUE TITLE
to generate an .exe

### ISSUE THREAD

**Issue by LennonPereira** [Xzandro/sw-exporter#101]
Sorry for my ignorance but as I am C # developer I do not know how to generate an .exe from this project, could you help me?

**Comment by Xzandro** [comment]
Its described in the readme. https://github.com/Xzandro/sw-exporter#building-packages

**Comment by LennonPereira** [comment]
I have seen this information, but I have not yet succeeded in generating an exe. I need to make a change in the function where I get the IPs because I need to return the sternal IPs since I want to run the application in a VPS

**Comment by Xzandro** [comment]
There are no headless versions of electron apps yet so its probably not possible. Your case is very specific so you might need to learn node / JS programming to do the change yourself. Its pretty straight forward anyway. But as I mentioned, you need some kind of UI do interact with SWEX.

**Comment by LennonPereira** [comment]
The change I can do because I will change this section:
getInterfaces () {
     this.addresses = [];
     const interfaces = os.networkInterfaces ();
     for (const k in interfaces) {
       for (const k2 in interfaces [k]) {
         const address = interfaces [k] [k2];
         if (address.family === 'IPv4' &&! address.internal) {
           this.addresses.push (address.address);
         }
       }
     }
     return this.addresses;
   }
I'm going to change to return a fixed IP.
I'm researching Node.js to learn how to generate an exe with change

**Comment by Xzandro** [comment]
YOu dont need to research anything on how to generate an exe. Everything is explained in the readme of this project. As I also said, you need some kind of UI acess, which most VPS dont provide. YOu can start it via commandline etc.

**Comment by LennonPereira** [comment]
I managed to generate the exe with the guidelines, but it did not work, I have a VPS windows in amazon I figured that if I put my real IP in SWproxy I could use it hosted in VPS, but unfortunately it did not work out

**Comment by LennonPereira** [comment]
Thank you very much for your attention.

**Comment by LennonPereira** [comment]
I hope one day you have a SWProxy to run on a VPS.
