### ISSUE TITLE
Game stuck on loading screen. HELP!!!

### ISSUE THREAD

**Issue by EAi3** [Xzandro/sw-exporter#105]
I've been using the exporter for the past few months and now all of a sudden it doesn't load game after I put Server and Port. Just stays on black screen for a couple minutes then says "Failed to Connect". HELP please!
Thank you!

**Comment by Xzandro** [comment]
99% of the errors are caused by false IP / Port entered in the Wifi settings or a security software is blocking the access (firewall etc.). Keep in mind that Windows also has a firewall. I recommend to deactivate it or just set an exception for private & public network access.
