### ISSUE TITLE
game wont load

### ISSUE THREAD

**Issue by bxriichiie** [Xzandro/sw-exporter#107]
i downloaded the proxy putting the ip and proxy numbers in and it still wont work. I am on windows 10 so im not sure if there is suppose to be another one because i tried all of them and none will work

**Comment by Xzandro** [comment]
99% of the errors are caused by false IP / Port entered in the Wifi settings or a security software is blocking the access (firewall etc.). Keep in mind that Windows also has a firewall. I recommend to deactivate it or just set an exception for private & public network access.
