### ISSUE TITLE
"Failed to connect with the network. Please try again later.(7)"

### ISSUE THREAD

**Issue by TheCourierr** [Xzandro/sw-exporter#111]
Its used to work in my old phone(Iphone 5), the new one i have is a S7 Edge. Either way now tried it in both of them and it doesn't work.
my anti virus is ESET, i have turned the firewall off and it still not works.
Thank you for your help in an advance.

**Comment by ViniciusVR** [comment]
I have the same problem. I used to use this a lot but after I updated my phone to the latest IOS version I couldn't connect to the proxy anymore. When I set it on my phone as I used to do and open the game, it takes a long time to load and displays the message "Failed to connect with the network. Please try again later. (7)". (Please help! my runes are all messed up! lol)

**Comment by GHMouse** [comment]
I am having the same issue...I think Com@uS is blocking access

**Comment by Xzandro** [comment]
Nope. 99% of the errors are caused by false IP / Port  entered in the Wifi settings or a security software is blocking the access (firewall etc.). Keep in mind that Windows also has a firewall. I recommend to deactivate it or just set an exception for private & public network access.

**Comment by LumiStar2000** [comment]
I could not get it working with any settings on my laptop via Wi-Fi.  Tried disabling all software firewalls, used both bands (2.4 and 5), manually set local IP's, enabled port forwarding, even set DMZ.  Nothing worked.

  Switched to my desktop via Ethernet, worked perfectly without any settings changes (plug and play).  Only had to hit "allow" on the Windows Firewall warning.

**Comment by AizenSousuke** [comment]
@LumiStar2000 maybe your router is preventing the laptop n phone to communicate together but not for desktop and phone. Currently I'm facing the problem too. I made my computer(in your case should be your laptop) set up its own adhoc network via wifi card and use my phone to connect to it directly.

**Comment by Xzandro** [comment]
If you really disabled firewall etc. You could try out my new tool SWEX Web and see if it works with that: [SWEX Web](https://swex.swop.one/)
