### ISSUE TITLE
Unable to connect, proxy error in game.

### ISSUE THREAD

**Issue by Kisageru** [Xzandro/sw-exporter#112]
I am on android and windows 7 and I have input the correct IP address and port into my android device for the proxy as well as allowed the firewall to connect on public and private networks, I have added the exporter as an exception in the firewall and disabled the firewall entirely all to no avail. I have seen your comment about the 99% of the time it's your fault and I can guarantee I am using the correct proxy details.
The only thing I have not tried (and can't try) is plugging my PC directly into my router as my PC is currently on wireless.

Any help would be appreciated.

**Comment by Xzandro** [comment]
You could try to restart all devices and also reset your Wifi. Other than that, I didnt lie, pretty much all issues were caused by weird security software. Maybe you have more than one installed?

Sadly I have no other solutions for you and it still seems to work for everyone so far.
