### ISSUE TITLE
No Teamlogging in RIFTDungeon

### ISSUE THREAD

**Issue by MaryLightning** [Xzandro/sw-exporter#114]
Hello,

i run rift and the log is not complete.
date,dungeon,result,time,item1,item2,item3,drop,grade,sell_value,set,efficiency,slot,rarity,main_stat,prefix_stat,sub1,sub2,sub3,sub4,team1,team2,team3,team4,team5,team6
2017-12-28 14:48,Rift Dungeon - Fire Beast,Did not kill,,Flaming Fire Crystal x1,,,,,,,,,,,,,,,,,,,,,

For me it is not interesstes if i kill or not kill rather i get the alphabetic character or which points.

Thank you

**Comment by msteudel** [comment]
I was noticing the sam thing. @MaryLightning  what does "get the alphabetic character" mean?

**Comment by MaryLightning** [comment]
Hello, if i play the beast i see how many damage and which mark i get. ( A+ A A- B+ B B- ....).

In worldboss it logs the grade.
Date,Boss #,Attack Power,Elemental Bonus,Damage,Grade,Mob 1,Mob 2,Mob 3,Mob 4,Mob 5,Mob 6,Mob 7,Mob 8,Mob 9,Mob 10,Mob 11,Mob 12,Mob 13,Mob 14,Mob 15,Mob 16,Mob 17,Mob 18,Mob 19,Mob 20
2016-12-12 10:40,63,75845,861,796001,C,Veromos,Kaito,Dagora,Bernard,Draco,Teon,Inugami (Water),Fran,Arang,Mina,Sieq,Lulu,Tarq,Ramagos,Mav,Ling Ling,Qebehsenuef,Geoffrey,Susano,Konamiya (In Storage)

thx :D

**Comment by Xzandro** [comment]
Old, if this error still consists, feel free to create a new issue with more details.
