### ISSUE TITLE
Builds number in the optimizer tab does not display correctly.

### ISSUE THREAD

**Issue by robertodurand** [Xzandro/sw-exporter#116]
When choosing a monster, specifying focus and putting data in the filters, the build number given at the top of the optimizer is not the same with the result of the builds found at the bottom of the spreadsheet. It seems as if the number given at the top of the optimizer is the result of the focus section only and not the focus + filter number.
![bug swop](https://user-images.githubusercontent.com/24474520/35787749-e24f5d58-0a06-11e8-842a-45486e6f2bef.png)

**Comment by robertodurand** [comment]
Browser Google Chrome - Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by Xzandro** [comment]
This is not the right place to report bugs of SWOP. This repo is about SWEX only.
