### ISSUE TITLE
Is it possible to build sw-exporter as a webapp or progressive webapp ?

### ISSUE THREAD

**Issue by RaspFR** [Xzandro/sw-exporter#117]
As sw-exporter is html/javascript based, I assume it would be relatively easy to build it as a web app or progressive web app in order to be able tu run it directly from our mobile phone.
Is it possible for you to do that ?

Thanks.

**Comment by PeteAndersen** [comment]
No, it relies heavily on NodeJS system APIs and cannot run only in a browser.

**Comment by RaspFR** [comment]
Even by using Node.js mobile ? 
[https://code.janeasystems.com/nodejs-mobile](url)

**Comment by Xzandro** [comment]
I'm not a huge fan of this idea. Having sw-exporter on your mobile phone makes it one thing: detectable. I will leave it open in case someone wants to make it. As for me, I dont plan to implement it.

**Comment by RaspFR** [comment]
You make a point. I get it :).
Thanks for the answer.

**Comment by Xzandro** [comment]
I built SWEX Web if you are still interested in a browser version: [SWEX Web](https://swex.swop.one/)
