### ISSUE TITLE
File Path Changes

### ISSUE THREAD

**Issue by CthulhuDancing** [Xzandro/sw-exporter#118]
Noticed when changing the file path for Data Files that if you set it to a path that is already created you get the following errors on start up
![image](https://user-images.githubusercontent.com/30942376/36065852-2aa8f718-0e66-11e8-9625-ad2723e4c815.png)
If you set the path to a folder that has not been created yet, it works fine.

**Notes:**
First tried renaming the folders. Then Tried Clearing all files in the folder and the Live Folder. When that didn't work i tried deleting the folders themselves. Checked permissions, 
This was tried on a folder that is syncing to both local PC and OneDrive.
Program Starts Normally after receiving errors, but does not load all elements of the page. (none of the plugins etc.)

**UPDATE:**
Error popped up again after completing a Dungeon run (and im assuming when trying to create a LiveSync File or some other plugin. Reverting to Last known good config to see what happens.
**UPDATE:**
Following error only occurs when receiving a rune from the run and seems to be linked to LiveSync
Also here is the Full Log 
[full_log.txt](https://github.com/Xzandro/sw-exporter/files/1713714/full_log.txt)

![image](https://user-images.githubusercontent.com/30942376/36065985-c1dc0110-0e67-11e8-81c6-03cce42cecd3.png)

**Comment by Xzandro** [comment]
This issue is solved. OneDrive issue.

Dont check this option: 
![grafik](https://user-images.githubusercontent.com/3385521/37444594-c8f35a6a-2812-11e8-945b-a29ad711b20c.png)

You will have placeholders if you do.
