### ISSUE TITLE
CDMG Enchanted Gems wrong mapping

### ISSUE THREAD

**Issue by 5diestel** [Xzandro/sw-exporter#120]
While building a tool to analyze my raid drops I kept getting an error when trying to map the min values of the drops to the rarity. So I checked my summoner-raid-runs.csv file and it says that I got a 3-6 CDmg Enchanted Gem which isnt possible in R5 since the blue ones are 4-6. So I checked your mapping.js and it turns out that it has
```
10: {
      range: {
        1: { min: 1, max: 3 },
        2: { min: 2, max: 4 },
        3: { min: 3, max: 6 },
        4: { min: 5, max: 8 },
        5: { min: 7, max: 10 }
      }
```
instead of 
```
10: {
      range: {
        1: { min: 1, max: 3 },
        2: { min: 3, max: 5 },
        3: { min: 4, max: 6 },
        4: { min: 5, max: 8 },
        5: { min: 7, max: 10 }
      }
```
[in Line 1165](https://github.com/Xzandro/sw-exporter/blob/master/app/mapping.js#L1165)
I'm actually not sure about the Common/White Gem since I dont have one to check the min/max and the wikia doesnt have it either

**Comment by 5diestel** [comment]
Something seems to be wrong with flat HP as well but the problem is not in mapping.js in this case.
Whenever I get a flat HP drop in raids the quality is increased by 1 in the run file:

Rare → Hero, Hero → Legend

I guess the problem must be in the run-logger then, I'll take a look at it

**Comment by Xzandro** [comment]
Thanks, small oversights. Grindstone and Enchanted Gems ranges were kinda unknown for a long time, especially low ranks.
