### ISSUE TITLE
Is it possible to get all defend team in siege

### ISSUE THREAD

**Issue by godshades** [Xzandro/sw-exporter#121]
Hi, thanks for awesome tool. But can we get list of all defend team in siege mode ?

**Comment by Xzandro** [comment]
Yes, pretty much every data you see ingame can be read with SWEX. I dont plan to make a plugin for this though so you would need to write it yourself.

**Comment by godshades** [comment]
Sr, How I can find the apiCommand's name
I don't know about nodejs but I will try use your profile-export.js for make the same thing

**Comment by t0v** [comment]
Simple answer No :(
You have to tap on each tower to get the list of units defending it.
When you enter the Siege screen, there is a GetGuildSiegeMatchupInfo request, but its response doesn't contain data for all the towers.
When you tap a tower, there is a GetGuildSiegeBaseDefenseUnitList request and its response has the units.

**Comment by godshades** [comment]
@t0v  Thanks for sharing. Can u help me make this plugin :(

**Comment by t0v** [comment]
https://github.com/Xzandro/sw-exporter/pull/124

I'm not sure, how useful this is. Like I said earlier, user needs to tap on each of the towers to get the list of its defenders.
Current implementation has a cosmetic bug:
- it shows the internal tower ID, which is not the same as Blue, Yellow, and Red base IDs shown on the client

**Comment by Xzandro** [comment]
Since this is not really an issue regarding SWEX itself, I'm closing this.
