### ISSUE TITLE
Which node and NPM version should be used?

### ISSUE THREAD

**Issue by t0v** [Xzandro/sw-exporter#122]
I get
```
Error: The module '.../sw-exporter/app/proxy/binaries/key-darwin-x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 57.
```

NODE_MODULE_VERSION 53 is not listed at all on https://nodejs.org/en/download/releases/

**Comment by Xzandro** [comment]
I recently updated the electron version, but I didnt compile the binaries for the electron version 1.8.2 yet (only for windows). I will do it shortly. Cant test them directly though.

**Comment by Xzandro** [comment]
Let me know if it works now. Its not really important which node version as long as its above electron's requirements (currently 8.2.1)

**Comment by t0v** [comment]
yep, that works.
tyvm!

**Comment by drickferreira** [comment]
I have the same issue...
Working on node 12.9
```
Error: The module '/sw-exporter/app/proxy/binaries/key-linux-x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 72.
```

**Comment by Xzandro** [comment]
This usually means, that your electron version is too high. Thats the reason we always have a fixed version of electron written in the package.json.
