### ISSUE TITLE
Connection Error timeout

### ISSUE THREAD

**Issue by Mace93** [Xzandro/sw-exporter#123]
Not able to connect to the game in spite of having restarted every device (Smartphone, Router, Laptop) and having totally deactivated my firewall as well as my antivirus programm....
Doesnt work....is there any chance to do it vice versa (Make my smartphone the mobile hotspot and let the laptop connect to this)?

**Comment by Xzandro** [comment]
The most common issues with SWEX are either entered the wrong IP / Port or a security software is blocking the access. So check your firewall (Windows has a built in one). You also could try to restart your laptop / router / smartphone.

**Comment by gojnimer** [comment]
I solve this problem 
1 - open the summoner wars and minimize 
2 -  change the proxy on the wifi config
3 - back do SW switch server and go back to your server
