### ISSUE TITLE
Failed to load page opening SW

### ISSUE THREAD

**Issue by ghost** [Xzandro/sw-exporter#125]
Used my phone shared the proxy followed everything opened SW or tried to. Failed to load page every time. Switched to my tablet same thing happened

**Comment by Xzandro** [comment]
The most common issues with SWEX are either entered the wrong IP / Port or a security software is blocking the access. So check your firewall (Windows has a built in one). You also could try to restart your laptop / router / smartphone.

**Comment by Cburgess0507** [comment]
yeah entering the ip and port would probably mean your blind

**Comment by Cburgess0507** [comment]
incorrectly*

**Comment by Cburgess0507** [comment]
Check the firewall? for what? to see if its running?

**Comment by Cburgess0507** [comment]
everything is already cleared to pass thru the firewall

**Comment by Cburgess0507** [comment]
I think your system is broken

**Comment by Cburgess0507** [comment]
never mind just had to change the firewall settings

**Comment by Xzandro** [comment]
Wow, that was... a lot of spam. In 99% of the error cases its weird firewall settings.
