### ISSUE TITLE
TypeError: port option should be a number or string: null

### ISSUE THREAD

**Issue by Gamewalker** [Xzandro/sw-exporter#128]
Hello,

getting this exception like every 10 minutes and need to stop and start proxy.

https://suckmypic.net/9pfEraCu.png

**Comment by Xzandro** [comment]
Duplicate of #74

**Comment by Gamewalker** [comment]
I changed my server completly and on a fresh Windows Server 2016 wothout any Antivirus/FW enabled or even installed it happens constantly.
