### ISSUE TITLE
Connection Error Public Network

### ISSUE THREAD

**Issue by Acetlo** [Xzandro/sw-exporter#130]
I've read the posts dozens of times, so I'm familiar with the most common solution to connection issues. However I'm stumped. At my University I tried connecting with the internet at the dorm, and when I opened sw after, inputting the proxy settings, the screen would turn black, and after about 5 minutes would give me the connection error. I manually disabled Windows Defender firewall, removed/re-added the app to the firewall settings, and yielded the issue. I went to the Library and tried the internet (they use a different isp) and met the same fate. I input and deleted the proxy settings dozens of times to be sure that I was not making any errors on that part.

Does it not work with public networks?

I'm using windows 10, iOS 10.3.3, and what is labeled a "Public Network" (if that helps). 

(EDIT) Same issues with SWProxy

**Comment by PeteAndersen** [comment]
There's a common security feature on public wifi networks called Client Isolation, which prevents one wifi client from talking directly to another wifi client. This sounds like Client Isolation to me, in which case it will not be possible for the proxy to work.

**Comment by Acetlo** [comment]
That makes sense, thanks for replying so fast.
Is there a way to overcome this issue on a public network? Or would I literally need access to the router to fix that?

**Comment by Xzandro** [comment]
I dont think there is a possibility unless you are the sys admin. You could try my new tool called SWEX Web you could help you out here. [SWEX Web](https://swex.swop.one/)

**Comment by Xzandro** [comment]
You could create one. And I know that SWEX Web is not free, but if you want to try it out, contact me via Patreon, reddit (Xzandro) or Discord (Xzandro#0001)
