### ISSUE TITLE
it does not save the .json file

### ISSUE THREAD

**Issue by johan1992** [Xzandro/sw-exporter#132]
Since two weeks ago I do not want to save the json file, I have installed the 32 and 64 bit version, and it still does not work, I also test with the portable versions and neither, please help, sorry for my bad English.

**Comment by Xzandro** [comment]
This is probably a firewall issue. Make sure you set an exception for SWEX, or disable it during the process.

**Comment by johan1992** [comment]
I also see that when I install it, the program pretends to install, but when I check installed applications SWEX does not appear, in the previous version if it appeared installed.

**Comment by Xzandro** [comment]
After every update you need to set a new exception to the firewall. It's important. If this not an issue please provide detailed information about what's not working. App does not open? Can't connect to the game?

**Comment by johan1992** [comment]
The program starts normal, I enter the proxy on my cell phone, I start the normal game and the program runs normally, it shows that the json file was created, but I look at the path where the files are created and there is nothing, I check all my pc and it is not anywhere.

**Comment by Xzandro** [comment]
Can you look in the Settings of SWEX? There should be a Files path. There you can find your files, by default its Desktop/Summoners War Exporter Files.
