### ISSUE TITLE
Logging Information from Profile in Chatroom

### ISSUE THREAD

**Issue by MaryLightning** [Xzandro/sw-exporter#134]
Hello,

its great. Thank you for TOA update. ^^

The last update on 27.04.2018 v3.8.5 have a very good feature.
The new Profilewindow from other Accounts with there Teams for Rift and Cairos-Dungeons.

I am happy for this Change. 

If i looks correct, is the API Request GetLobbyInfo for first Information and GetLobbyWizardLog for the three protocol (Teams) pages.

It were a dream to logging this Information too. :)

Very very Thanks for realize this Question. :D

Mary

**Comment by woodsy1** [comment]
#155

**Comment by Xzandro** [comment]
Old, outdated and probably not being actively worked on.
