### ISSUE TITLE
Proxy Error, unable to load game

### ISSUE THREAD

**Issue by dragonisk** [Xzandro/sw-exporter#135]
I've used SWEX before without a problem on my laptop which connects to our router via WiFi. However, since I've bought a desktop which connects via ethernet cable on the same router, I have been unable to use SWEX as it always gives the proxy error. Even other apps won't connect to the internet. I've entered all settings correctly, Windows Firewall is OFF as well as Avast Shields Disabled permanently (at least until I turn them back on), SWEX is running as admin.

Is there something I'm missing? Is wifi to ethernet not possible?

EDIT: Weirdly enough, facebook's Messenger app works without a problem. I'm confused.

**Comment by Xzandro** [comment]
As long as both devices are in the same network it should work. Well, if you really are sure you entered IP and port correctly AND no security software is blocking the acces... I'm pretty much out of ideas. :/

**Comment by tuscanspeed** [comment]
Check your router for a setting called "Wireless Isolation"
My Netgear by default forbids communication between the Wifi zone and the Ethernet zone.

**Comment by dragonisk** [comment]
sorry for the very very late reply but just so the issue has an actual resolution: Yes, there was an isolation happening. Thanks to tuscan for helping me figure it out!
