### ISSUE TITLE
Can't connect to the internet when I set proxy to manual

### ISSUE THREAD

**Issue by zaruchimu** [Xzandro/sw-exporter#138]
Hey guys! so... I have a situation
I've done everything the tutorials said, I've installed SWEX, clicked on Start Proxy, and I've gone to my phone in the wifi settings and set the proxy to manual, with the ip adress and port provided by SWEX. Although when I do the final step my phone loses connection with the internet, and I may have a clue of what is happening but no idea of what to do.

I tried to use sw-proxy and I got an error that I didnt find any mention on the internet regarding swarfarm or optimizer:

Error running proxy server (Error 10013): An attempt was made to access a socket in a way forbidden by its access permissions.

So I guessed that my system some how is blocking port 8080, I disabled all Firewalls, even opened and rule exception to port 8080, NOTHING

So I would really appreciate some help, and sorry about my english, it is not my first language so if you dont understand something just let me know

**Comment by Xzandro** [comment]
Well, did you try to change the port? Just enter another one and stop / start the proxy. Dont forget to change the port in your Wifi settings too.

**Comment by zaruchimu** [comment]
Wow it worked, I feel so stupid that the solution was that simple, probably the PC was blocking the port 8080, adding something here, I was helping a friend going through the same problem, and we found out that it is not just any number that you put on the port, with both of us worked with port 2000.
REALLY APRECIATE IT

**Comment by Xzandro** [comment]
Perfect. :)
