### ISSUE TITLE
[Suggest Plugin] Is it possible to export Enemy's Monster info after start RTA Battle?

### ISSUE THREAD

**Issue by A1Darkwing** [Xzandro/sw-exporter#139]
Its really help to determine which monster should be focused based on their defend and hp when we battle on RTA
.
I can saw that the Log file export something like : 
...
units":[{"pick_slot_id":2,"...{"rune_id":4230527962,"wizard_id":56209,"occupied_type":1,"occupied_id":3006647243,"slot_no":4,"rank":5,"class":6,"set_id":17,"upgrade_limit":15,"upgrade_curr":15,"base_value":570600,"sell_value":28530,"pri_eff":[10,80],"prefix_eff":[0,0],"sec_eff":[[8,4,0,2],[1,335,0,384],[9,21,0,0],[4,6,0,5]],"extra":0}...

**Comment by A1Darkwing** [comment]
Beside that, I wrote small robot to do some click on window after I read the log & csv file. It help me auto farm dragon. Thank you so much for your powerful tool

**Comment by Xzandro** [comment]
I will not help with potential cheat or bot tools.
