### ISSUE TITLE
Nav buttons don't work reliably 

### ISSUE THREAD

**Issue by Sebacore** [Xzandro/sw-exporter#14]
The navigation buttons don't always work in 0.0.9.

**Comment by Xzandro** [comment]
Can you elaborate a little bit more? Do you mean the Logs, Settings etc? Which OS? Any errors in the console (if you hit CTRL + Shift + i -> Console)?

**Comment by Xzandro** [comment]
Ahh, I see, ther eis an error if you click on Information in the WIndows versions. That wasnt a bug in the code. It was a packaging error. I reuploaded the Win packages. Should work now. COnsider to redownload the package. :)
