### ISSUE TITLE
To Try bar and debian version

### ISSUE THREAD

**Issue by Albrod** [Xzandro/sw-exporter#147]
Hi, first i want to thanks the owners of this project then i want to ask for two functions if they can be done.
First if it is possible to add a function to minimize/close to trybar and to start it minimized.
Second a debian friendly version or atleast a terminal version simple just start proxy at x ip and y port and log everithing.

**Comment by Xzandro** [comment]
Hi, not really into Linux honestly, but if anyone wants to implement this, I wouldn't mind a PR.

**Comment by Psifour** [comment]
Can we get this renamed and tagged? It is a feature request for a task bar icon (which can be done cross-platform in electron).
The other portion of the request is duplicated in #108 

I can start smashing it together. What menu items beyond "Open" and "Quit" would you want implemented? A toggle to turn the proxy on/off and a text field to show the current ip/port?

**Comment by Albrod** [comment]
:D
With Open, On/Off, one to open the website (https://tool.swop.one/) or another good site to use the json files and quit button will be enough i think. Also it can be add to linux ?

**Comment by Psifour** [comment]
I am a Linux user and can confirm that the pull request I submitted functions on Linux. It should function on Windows/MacOS as well (may need some tweaks to size/format of the icon png).

Currently it has On/Off and Quit, but adding additional controls is trivial. I am wary of adding them without guidance from @Xzandro though as this is his project and I won't just make promises of features without his consent.

**Comment by Albrod** [comment]
@Psifour thank you very much.

**Comment by Xzandro** [comment]
Tray icon is implemented in SWEX, so I will close this now.
