### ISSUE TITLE
SW will not run with proxy enabled on phone.

### ISSUE THREAD

**Issue by LSharpAura** [Xzandro/sw-exporter#148]
Every time I've tried to run this app and set up the proxy on my phone, SW runs up to the point where the title screen would come up.  After that I get a black screen for a while and then an error saying it can't connect to the network.  If I disable proxy, everything works fine.

Running as admin on Windows 10.

**Comment by Xzandro** [comment]
The most common issues with SWEX are either entered the wrong IP / Port or a security software is blocking the access.

**Comment by LSharpAura** [comment]
Firewall is off and I triple checked my ip so not sure what else it might be.  I got the file using your web version so it's definitely something with the desktop.

**Comment by Xzandro** [comment]
Hmm, hard to say. Are you in a University network or other restrictive networks? Maybe your router has some kind of wifi client isolation? Maybe you have another firewall or antivirus installed on your PC that interferes? That's the beauty of SWEX Web, you don't have to worry about such things at all.

**Comment by TnT4u** [comment]
I just updated Malwarebytes the other day and it is causing the issue. I haven't narrowed down what is causing it but it has to do with the real time protection.

**Comment by LSharpAura** [comment]
Disabling Malwarebytes rt protection does seem to make it work now.

**Comment by Xzandro** [comment]
Yea, it's definitely Mailware Bytes. I heard that from other people too. I recommend the usage of Windows Defender. Its a very good anti virus software nowadays and doesnt cause issues constantly.
