### ISSUE TITLE
No wifi

### ISSUE THREAD

**Issue by PeanutMonkeyG** [Xzandro/sw-exporter#151]
Hi, i only have access to a shared wifi so using the proxy the way we are supposed to doesn't work, is there any other way to make it work? like mobile data, hotspot, bluetooth?

Thanks.

**Comment by Xzandro** [comment]
Well, there is another possibility, but it's not free. Its called SWEX Web: https://swex.swop.one/ It's a tool where I provide the proxy and files on my own server and you can just connect through that.
