### ISSUE TITLE
Profile not updating

### ISSUE THREAD

**Issue by agliu** [Xzandro/sw-exporter#152]
I'v had trouble for awhile updating my profile on SWFARM. I have the "Profile Export" option selected and it seems like the only way to update the profile is to completely uninstall and reinstall.

**Comment by agliu** [comment]
It doesn't update the monsters in my profile. It generates a new "Live" log but outside of that, no other JSON file.

**Comment by Xzandro** [comment]
Ehhh, to update your profile you need to import a complete new JSON file. There is no live sync for swarfarm.

**Comment by agliu** [comment]
Gotcha, that JSON file isn't being generated for me. I thought it was folder permissions but that was not the case.

**Comment by ianchudson** [comment]
The file in question is the standard full json file, the one you also use for SW.OP, if that file isn't being created (have to be connected to the proxy when you launch the game), then you have bigger problems I would imagine.

**Comment by ianchudson** [comment]
Clarification:

1. Close Game Application on Phone
2. Start Proxy
3. Connect Proxy on Phone
4. Launch Game

As soon as you get through the game launch and see the island, this should always create your profile file. If not, something is wrong with your setup.

**Comment by agliu** [comment]
Ah ok that worked. TIL order matters. Thanks!
