### ISSUE TITLE
Error in Summoners.War.Exporter-0.0.23-linux.AppImage and fixed version

### ISSUE THREAD

**Issue by keeperxy** [Xzandro/sw-exporter#157]
Hey,

AppImage 0.0.23 has this error:

> ./Summoners.War.Exporter-0.0.23-linux.AppImage 
> module.js:487
>    throw err;
>    ^
> 
> Error: Cannot find module '/tmp/.mount_SummonX3v3df/resources/electron.asar/browser/init.js'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Function.Module.runMain (module.js:605:10)
>     at startup (bootstrap_node.js:167:16)
>     at bootstrap_node.js:589:3

I looked into it (cause 0.0.22 has not any error) and found the following:

> ./Summoners.War.Exporter-0.0.23-linux.AppImage --appimage-extract   
> ...
> squashfs-root/resources   
> squashfs-root/resources/app-update.yml   
> squashfs-root/resources_1   
> squashfs-root/resources_1/app.asar   
> squashfs-root/resources_1/electron.asar   
> ...

It seems something with the resources folder is wrong, so i moved everything from resources_1 to resources and deleted resources_1 and created a new AppImage:

> ./appimagetool-x86_64.AppImage squashfs-root Summoners.War.Exporter-0.0.23_1-linux.AppImage

And now everything works fine.

I talked to @Xzandro and gave him the new AppImage.

Regards
KeeperXY

**Comment by Xzandro** [comment]
I uploaded this AppImage and hope all the issues are solved now.
