### ISSUE TITLE
JSON File Limited to 24 Mons

### ISSUE THREAD

**Issue by Finchuna** [Xzandro/sw-exporter#158]
Hi,
The json file export I pull and import is limited to 24 mons, I have 106. Any settings that need to be adjusted that you know of?
Thanks.

**Comment by Xzandro** [comment]
I dont really know what you mean with that. Its not limited at all. Are you sure, that you are using SWEX? What tool do you import the file into? Either way, it's probably not an issue with SWEX, but I will leave it open a few days.

**Comment by Finchuna** [comment]
Hi,
I'm saying that I've used Summoner's War Exporter to create json files, and
each time I've done so, when I import the file into Summoner's War
Optimizer, only 24 mons are imported. I've attached the json file for
reference. I'm not sure how to read the json file when I open it in notepad
so I can't tell if the json file is being created accurately and the
Optimizer isn't loading it completely or the problem is with the json file.
Thanks for your response and help.

**Comment by Xzandro** [comment]
I dont think I can see the JSON file,. but I'm pretty sure its some issue with your Summoners War Optimizer import settings. SWEX always exports the complete and unchanged data from com2us. There is no monster or rune limit.

**Comment by keeperxy** [comment]
Do you check "Don't import monsters without runes" and "Don't import monsters with grade < 6 (monsters with runes equipped will be imported regardless)" in SWOP? Just an idea, cause the export from SWEX always exports the complete data.

**Comment by Finchuna** [comment]
Yea, the "Don't import monsters with grade <6" was it; noticed it about 20
min before you sent this. I'm an unobservant idiot. Sorry to waste your
time, but great suggestion.
