### ISSUE TITLE
ERR_FILE_NOT_FOUND when reloading

### ISSUE THREAD

**Issue by GuiCavi** [Xzandro/sw-exporter#159]
I just cloned the project and did the basic

1. npm install
2. npm run dev
3. npm start

In chromium console, it appears
`You might need to use a local HTTP server (instead of file://)`

Then, if I reload the app, it prints:
`GET file:/// net::ERR_FILE_NOT_FOUND`

I didn't changed anything yet, just cloned, started and reloaded. Did I miss something?

**Comment by Xzandro** [comment]
That's weird. Did you try it multple times? `npm run dev` is just for hot reloading and to produce the bundled file so in theory you should run it once and that's it, but you could try to let it run and do the `npm start` in an extra terminal.

**Comment by GuiCavi** [comment]
Both ways it failed to reload. I tried all afternoon today. Can you reproduce that too or it's just me?
