### ISSUE TITLE
i can use bluestacks with thiss?

### ISSUE THREAD

**Issue by ZergShadow** [Xzandro/sw-exporter#160]
i can use bluestacks with thiss?

**Comment by Xzandro** [comment]
I think you can. I only tried it with nox tho. No real experience with bluestacks.

**Comment by ZergShadow** [comment]
i dont know where in bluie stacks i should enter proxy addreesss

**Comment by ZergShadow** [comment]
i found wifi setttings in nox.but no in bluestacks.
