### ISSUE TITLE
Failed to run on 32-bit ARM

### ISSUE THREAD

**Issue by zerg960** [Xzandro/sw-exporter#168]
Trying to get sw-exporter running on a Raspberry PI 3 B+. So far I haven't had any real problems following the readme. There's a similar (now closed) issue #66

Running `npm start` inside a remote desktop session on the pi (running over ssh gives unhelpful errors) gives me:
```
$ npm start

> sw-exporter@0.0.23 start /home/pi/summoners/sw-exporter
> electron .

App threw an error during load
Error: /home/pi/summoners/sw-exporter/app/proxy/binaries/key-linux-arm.node: wrong ELF class: ELFCLASS64
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/summoners/sw-exporter/app/proxy/smon_decryptor.js:4:20)
    at Object.<anonymous> (/home/pi/summoners/sw-exporter/app/proxy/smon_decryptor.js:22:3)

```

Some more information:

```
$ file ./app/proxy/binaries/key-linux-arm.node 
./app/proxy/binaries/key-linux-arm.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b4f911434dbab30dc9f66e5289265887e43bc13d, not stripped

$ getconf LONG_BIT
32

$ cat /proc/cpuinfo
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
```

I console.logged the process variable in smon_decryptor. It has `"arch": "arm", "platform": "linux"`. There are no other values that indicate it's running on a 32-bit system.

Could you compile a 32-bit ARM binary? Thanks!

P.S: I now have everything working like it should be on the Raspberry Pi by hardcoding the correct decryption key in the JavaScript, updating Electron to v.2.0.9, and recompiling.

**Comment by InTimeZ** [comment]
> P.S: I now have everything working like it should be on the Raspberry Pi by hardcoding the correct decryption key in the JavaScript, updating Electron to v.2.0.9, and recompiling.

Hi, can you explain how you have done that? I`m new in working with a Raspberry Pi, but I wanted to get the sw exporter running on it.

**Comment by Xzandro** [comment]
Just to make it clear before anyone posts here, I don't want the encryption key publically available. Yea, I know, it's not to hard to figure out anyway, but everything is better than plain-text in public.

**Comment by Xzandro** [comment]
Electron was already updated to 3.0.3. Regarding the 'memory' leak, its caused from the the log section. The more log entries are generated the slower it gets, because all the divs will be reinserted into the DOM, which takes longer and longer. This is more of an oversight than anything else probably.
It might be needed to discard entries after a set number or do lazy loading of these. But then again, SWEX was never created with servers in mind or to run permanently. Usually you use it a few minutes and get the job done.

**Comment by InTimeZ** [comment]
> Usually you use it a few minutes and get the job done.

Yeah you`re right, it`s just a raspi hobby and would be nice to have a full log with all run`s, but that`s not that important.  Thanks for the explanation :)

**Comment by DerDu** [comment]
btw: still an issue regarding op ;)

Issue: Failed to run on 32-bit ARM
Request: Could you compile a 32-bit ARM binary? Thanks!

**Comment by Xzandro** [comment]
Closing this in favor of #162
