### ISSUE TITLE
White screen when running on Raspberry PI

### ISSUE THREAD

**Issue by zerg960** [Xzandro/sw-exporter#169]
Running `npm start` on a Raspberry PI 3 B+ (linux-armv7 32-bit) results in a white window with the title "Summoners War Exporter".

Upgrading dependencies to electron v2.0.9 resolves the issue. (See https://github.com/electron/electron/issues/11877)

If I can get the proxy doing proxy-things on Raspberry Pi, I'll submit a pull request to do just that.

**Comment by Xzandro** [comment]
I hope this is fixed. Upgraded to electron 3.0.3 in master.
