### ISSUE TITLE
Headless VPS Setup Issues

### ISSUE THREAD

**Issue by kmorton1988** [Xzandro/sw-exporter#171]
I bring little knowledge as to how all the pieces as a whole work together, but I am having issues setting this up to run on a headless VPS. On the README doc, it shows that there's a way to do this, but I keep getting stuck on the fact that the GUI aspect (electron) is either not showing up or not installing. Is there a way around this? Is this even possible yet? 

I apologize is this is the wrong place to post about this, but I have been working at this for hours with little success.

**Comment by Psifour** [comment]
This is touched on in #108 and #109 and effectively duplicates that issue/pull request. If you need this NOW I would personally recommend using something like Xvfb to create a virtual display for it to run in.
