### ISSUE TITLE
Java script error when building_list is undefined

### ISSUE THREAD

**Issue by Lejoon** [Xzandro/sw-exporter#173]
<img width="796" alt="screenshot 2018-10-14 at 08 10 30" src="https://user-images.githubusercontent.com/843686/46913332-6fece500-cf8b-11e8-81f5-f3196518c8da.png">

**Comment by Psifour** [comment]
For anyone working to debug this the relevant line number is two lower than the error indicates. This is due to a change in #176 
It would appear that somehow the events that profile-export was listening for (HubUserLogin and GuestLogin) received an undefined response object. 

My suggested solution would be to check for undefined request and response data before emitting the events at https://github.com/Xzandro/sw-exporter/blob/1bd70f2129a370c297552935aff5c2d83d97fb2e/app/proxy/SWProxy.js#L55

**Comment by Xzandro** [comment]
This issue is in this line.
https://github.com/Xzandro/sw-exporter/blob/1bd70f2129a370c297552935aff5c2d83d97fb2e/app/plugins/profile-export.js#L50
For some reason, sometimes com2us just doesn't send the `building_list`property for totally unknown reasons. This error is super rare tho.

**Comment by Psifour** [comment]
I had considered that, but doesn't the "of undefined" indicate that the object we are acting on (data) is undefined? If not than I apologize for complicating the issue by going further back in the stack than was necessary.

**Comment by Xzandro** [comment]
Nope, for ... of requires an iterator property to work, since `building_list` is undefined, it also doesn't have a iterator property. I know the issue, but since we need this property to figure out the storage_id and since the error is kinda rare I just left it untouched for now.

**Comment by Psifour** [comment]
How would you feel about me adding a check for `building_list` being undefined and just turn off or skip sorting in that case? It isn't an elegant solution, but would allow it to fail with an error in the log instead of a popup.

**Comment by Xzandro** [comment]
Thought about it, don't really know. People are REALLY used to the sorting and would be super confused if monsters are not sorted or marked in storage. I rather would people to force to do the process again than not having this. As I said, this is absolutely rare. I have SWEX Web running on my server and a few hundred users use it daily and only saw it 1 time over a period of months. Low priority.

**Comment by Psifour** [comment]
Will comply. I personally don't use the sort as the tools I use provide sorting/filtering options, but I could see how that would bother users using other tools.

**Comment by deakaii** [comment]
Getting the same issue for the first time running Bluestacks and SWEX v0.0.3. Worked well since the HTTPS issue until today.

**Comment by deakaii** [comment]
@Xzandro After weeks of success I'm now receiving this error consistently on V 0.0.3.

**Comment by Xzandro** [comment]
I think we can close this for now. It should be rare that this error happens and it's also caught probably since a few versions ago.
