### ISSUE TITLE
live sync and raid grindstone

### ISSUE THREAD

**Issue by Lorryanna** [Xzandro/sw-exporter#177]
Hi

Got this error in Summoner Wars Optimizer with Live Sync On
![capture](https://user-images.githubusercontent.com/8207755/48454817-1f9aba00-e7b9-11e8-978f-b240e59ad8dc.JPG)
I dont know if it's the optimizer not able to manage the json from SwEx or if SwEx fails to create a correct file.

Content of the live file, it's created during a rift raid (grindstone in this case, don't know if the error occurs with enchantment too)
```
{
  "wizard_id": xxxxxxxx,
  "timestamp": 1542160121,
  "action": "new_craft",
  "type": "raw"
}
```

edit: using SwEx v0.0.24 and optimizer v4.9.1

**Comment by Xzandro** [comment]
This usually means, that you choose the wrong folder in SWOP, or you have a file other than JSON ones in that folder. This is not a problem in SWEX regardless, so closing here.
