### ISSUE TITLE
There were errors importing your SWARFARM profile: [object Object]

### ISSUE THREAD

**Issue by MrSuricate2** [Xzandro/sw-exporter#179]
![capture](https://user-images.githubusercontent.com/29656351/48673857-2d986400-eb46-11e8-821f-ef10566b3413.PNG)
[full_log.txt](https://github.com/Xzandro/sw-exporter/files/2592840/full_log.txt)

**Comment by PeteAndersen** [comment]
Already resolved and awaiting release

**Comment by Benniphx** [comment]
I have still the error in v0.0.24. do you have a release date ?

**Comment by Xzandro** [comment]
We release new versions unfrequently. There are a few new things that we want to implement first and then I will do a new full release. No ETA.

**Comment by PeteAndersen** [comment]
The most likely cause is that you did not save your import options on swarfarm.com
