### ISSUE TITLE
NO .json file Mac OS 10.13

### ISSUE THREAD

**Issue by miNo-SW** [Xzandro/sw-exporter#181]
Hey guys.

I'm using a Mac on OS 10.13.6 And i got the log message: Saved profile data to .miNo-111026.json
Also i can see my farming results etc. in log. But i can't find the .json file. Although i changed the Files Path in the settings, there is no .json file. Any ideas how to solve?

**Comment by Xzandro** [comment]
That's odd. It should be on the desktop in the Summoners War Exporter files folder and yea, otherwise in the folder you chose. Soo... can't really explain this behavior.

**Comment by AerialJustice** [comment]
You are either behind a firewall, blocking the port you're using, or running the app in a container.

**Comment by Xzandro** [comment]
Closing, inactive.
