### ISSUE TITLE
Unable to paste SWARFARM API key into settings section on Mac

### ISSUE THREAD

**Issue by NJABreakdown** [Xzandro/sw-exporter#183]
There's no functionality to paste a SWARFARM API key into its section on the settings menu on the Mac version. Have to manually enter the value.

Currently running Mac OSX 10.14.1

**Comment by Xzandro** [comment]
Can't really reproduce. The usual copy & paste commands worked fine for me. Try Command + c to copy the API key and Command + v to paste it into the input field.
![grafik](https://user-images.githubusercontent.com/3385521/50100277-60567a80-0220-11e9-865a-92aa93b3401a.png)

**Comment by Benniphx** [comment]
confirm this issue, in Mac OSX 10.14.1 you cannot past in the api field

**Comment by Xzandro** [comment]
I googled a bit and it seems to be the case, that copy and paste doesnt work in Mac OS if you install from the normal package, since you need to bind to the native clipboard. Weird behavior.
