### ISSUE TITLE
Stuck on Black Screen

### ISSUE THREAD

**Issue by Bowlingfeend196** [Xzandro/sw-exporter#184]
I've used the tool tons of times and now for the first time (after not changing anything), I get stuck on the black screen when starting the game. I generally don't ask for help or tips because I can figure things out on my own but I've tried everything and nothing is working. What could have changed to cause this issue now?

**Comment by Xzandro** [comment]
I tested it on my computer and it seemed to work so we can rule out a general issue here. Honestly hard to say, the most common issue is a security software is blocking the access oir you entered the wrong IP / Port.

**Comment by Bowlingfeend196** [comment]
I know. Sorry for being so generic here. Was hoping maybe somebody knew something about an iPhone update that caused issues. Or a setting that may have been changed when my CPU or Phone updated. This is super frustrating. Do you know of any safe alternatives to this for exporting?

**Comment by Xzandro** [comment]
You could try [SWEX Web](https://swex.swop.one/), where you don't need any PC at all. It's not free tho.

**Comment by Xzandro** [comment]
Closing this, because it's probably not a general issue with SWEX itself, rather a network setup issue or some PC weirdness. In this case I know, that it worked with SWEX Web.
