### ISSUE TITLE
Can't connect no matter what

### ISSUE THREAD

**Issue by cderoche** [Xzandro/sw-exporter#186]
I can't get the extractor tool to connect with my LG V20 VS995 phone no matter what I try. I've allowed it access via the firewall, even disabled the Windows Defender program entirely and Malwarebytes, still nothing happens after trying to get the .json file. I am on Windows 10 and using the 64 bit version of the tool. I've double checked my proxy settings everything is how the tutorials show. I won't generate the file for me. Is there any other trick to get this file to extract?

**Comment by cderoche** [comment]
Update - does a VPN stop this process? I use DNS66 app I just remembered, and had it running in the background. I will try again with it off when I get time.

**Comment by Xzandro** [comment]
Yes, a VPN could create issues for sure.

**Comment by cderoche** [comment]
OK that's good to hear, I can't try it at work right now they block SW via their WiFi but I'll try again once I get back home, and try to update here if it works.

**Comment by cderoche** [comment]
I disabled the VPN and the json file was extracted no issues. Good to know! Thanks for the help also!
