### ISSUE TITLE
Potentail Malware Issue

### ISSUE THREAD

**Issue by Nai81** [Xzandro/sw-exporter#188]
Hi guys,

I'm quite concerned about malware riding along. I am running malwarebytes premium. Today it has blocked multiple outbound connections to "imtrck.com", "tengo-deg.com", "sl.ivankatraff.com", "ashleyrnadison.com" (yes that's spelled right). These originate from the sw exporter.exe temp file.
Needless to say this is incredibly concerning. 
Can anyone clarify?

**Comment by PeteAndersen** [comment]
You might want to check your phone. SW-Exporter is an internet proxy, so any traffic appearing to come from it is sourced from something else.

**Comment by Xzandro** [comment]
Closing. It's just as porksmash said, the source of requests is never the proxy itself. We just intercept data.
