### ISSUE TITLE
Specify default network interface in options?

### ISSUE THREAD

**Issue by Jbag1489** [Xzandro/sw-exporter#19]
Not sure if this would be possible, but from having some virtual machine adapters, I'm always having to select from multiple IP addresses. Would be very nice if possible to set to always use a specific interface.

**Comment by Xzandro** [comment]
Thats not needed, because the proxy listens for every IP address by default. That select is purely for information purpose.

**Comment by Jbag1489** [comment]
Oh OK, cool
