### ISSUE TITLE
Can't get dungeon logs (win10)

### ISSUE THREAD

**Issue by Zhelyazkow** [Xzandro/sw-exporter#193]
Hey all, I just downloaded SWEX and it doesn't seem to have a problem, even when I imported the data in swarfarm, but it doesn't even let me click the "Data Logs". 
Thanks in advance! :)

**Comment by PeteAndersen** [comment]
Data logs are temporarily disabled. Check swarfarm.com for status updates, ETA is approximately 1 week.
