### ISSUE TITLE
JavaScript error occured in the main process

### ISSUE THREAD

**Issue by TortuousAugur** [Xzandro/sw-exporter#203]
None of the other reported issues seemed to have my error message, so here's mine:

I have SwarfarmLogger enabled since it wasn't giving me errors in the Logs screen. Don't know if that has anything to do with it or not.

This error pops up seemingly randomly while the program is running. I don't know if the proxy has to be actively running in order to get this error or not, I haven't tried any in depth troubleshooting on my end.

Once this error pops up, all traffic through the proxy is halted until the error is closed. I have tried reinstalling but I'm guessing there is some setup file somewhere that I'm unaware of because the error persists from a portable program on a thumb drive to a full install after removing the thumb drive, along with all settings. I wouldn't know if this settings file would be causing it, either....

![swexerror](https://user-images.githubusercontent.com/5731788/54875944-b7e32400-4dd5-11e9-98bf-c6f825143219.png)

**Comment by TortuousAugur** [comment]
I'm also now having the logger doing something that prevents the proxy system from working properly. There is no error but my game stops sending and receiving data shortly after launching the SWEX program.

**Comment by TortuousAugur** [comment]
I've decided to change the port the proxy was using. This seems to have fixed the issue. I've been running SWEX all day today and not a single error that I remember. Guess 443 is a registered port. Anyone else getting errors might try to use a port number between 50000-65535

**Comment by Xzandro** [comment]
Good to know. And yes, port 443 is a VERY important port and used for SSL (connections via https). Default port is 8080 and usually should be available.
