### ISSUE TITLE
How can i get summoning logging?

### ISSUE THREAD

**Issue by Starymary** [Xzandro/sw-exporter#204]
Hello,

how i can get the feature from SW-Proxy with log from summoning Monsters?

Very big Thank You.

StaryMary

**Comment by Starymary** [comment]
Hello,

i answer to me self.

Yes, you can find the summoning data in the Logfile there is in the Files Path that you set in the app-settings.
But you get not the *-summons.csv from SWProxy.

So i change my anser in:

The Log is with many times very big.
I like the old csv files. Can app the csv-files from SWProxy, too?

I have a computer with microsoft and i use Visual Studio Community Edition. I like sw-exporter to use with my visual studio to config the export in a database (ms sql). Give it a help to use sw-exporter with visual Studio?

Very great thanks

Best Regards

StaryMary

**Comment by Xzandro** [comment]
This is probably better done as an external plugin, because it sounds a bit niche. You can read about external plugins here: https://github.com/Xzandro/sw-exporter#developing-plugins
