### ISSUE TITLE
CSV Rune & Monster Only

### ISSUE THREAD

**Issue by saissiabdessamad** [Xzandro/sw-exporter#219]
Hi, 

is it possible to get a table with runes & Monsters only ? It would be more free to use and we may find more rune combination  ?

Cordialy

**Comment by Xzandro** [comment]
Currently this is not supported in SWEX. You can however import the JSON file in [SWOP](https://tool.swop.one/) and export from there as CSV.

**Comment by Xzandro** [comment]
Probably better solved as an external plugin.
