### ISSUE TITLE
Post Dimensional Hole Update issue

### ISSUE THREAD

**Issue by japurillo** [Xzandro/sw-exporter#220]
Seems like after the Dimensional Hole update its now broken and doesnt sync to SWFarm and logger errors out.

![Screen Shot 2019-06-13 at 8 09 34 PM](https://user-images.githubusercontent.com/5369389/59431369-57351780-8e17-11e9-8951-f5dcba6d2e06.png)

**Comment by Xzandro** [comment]
This is an issue in SWARFARM, since it doesn't support the new runes, gems and grindstones yet. I'm sure porksmash will work on this soon. Closing here tho.
