### ISSUE TITLE
Log not automatically showing latest events

### ISSUE THREAD

**Issue by Kevin-Mok** [Xzandro/sw-exporter#223]
## Expected Behavior

Log to update constantly and show the latest events.

## Current Behavior

Have to click to Settings or Help and then back to Logs to refresh and show the latest log events.

## Context (Environment)

Operating System: Arch Linux 5.1.8
Version: v0.0.26 (built using [README instructions](https://github.com/Xzandro/sw-exporter#building-packages))
Settings: 
![screenshot-2019-06-22_06:43:47](https://user-images.githubusercontent.com/25857736/59962926-f0b89500-94b9-11e9-9b35-3fec6a621d3a.png)

## Detailed Description

Unsure what the source of the problem is. Possibly settings-related?

**Comment by Kevin-Mok** [comment]
Started working after a restart.

**Comment by Xzandro** [comment]
Any more infos? I didn't look into it, but can you say when this happen exactly? Specific events? After a specific time frame? Any other things?

**Comment by Inceptorsummon** [comment]
I too am having the exact same problem.
It happens more commonly on dungeons I am noticing, not so much on scenarios. This is also occurring for the dimensional hole ancient runes.
My OS is win10 pro.
My settings are as per the attachment.
The workaround for me is the same, clicking on another menu item (settings or help) and then back to logs to make it display correctly.
![sw settings](https://user-images.githubusercontent.com/52205623/60100309-d07c2500-979c-11e9-8274-37b6cc3f6b1a.png)

**Comment by Xzandro** [comment]
This is probably related to the new 'Maximum amount of log entries' option and needs to looked into.

**Comment by EvilzGaming** [comment]
I have exactly the same problem, somebody have an issue?
Uninstal - reinstal swe for the 8 times.
My phone is a Mi8 - Android
Where i can found something who could you help you to found an issue?
![image](https://user-images.githubusercontent.com/53636535/62408284-d5679c00-b5c6-11e9-81a6-fe34b9a79b93.png)

**Comment by Xzandro** [comment]
This was an UI error only, caused by length check in the react `shouldComponentUpdate` function. Before the update with the maximum amount of logs, this never was an issue, since the length was never the same.
