### ISSUE TITLE
Issue with SW Exporter

### ISSUE THREAD

**Issue by joselinho621** [Xzandro/sw-exporter#225]
I have been always able to use the SW Exporter efectively but 2 months ago till now it does not work.

When I click on "Start Proxy" and launch the game it never extract the json file. I dont know what to do. I change port, switch off windows defender...but nothing. The program only says "Listening on por 8080 but never extract the info.

**Comment by Xzandro** [comment]
There is a Android 9 issue around. Read about it here: https://www.reddit.com/r/summonerswar/comments/ba21pf/swex_not_working_in_android_9/
There isn't really something we can do about it, so you have to do the workaround.

**Comment by PeteAndersen** [comment]
Closing since Android is the source of the issue
