### ISSUE TITLE
JavaScript error [ERR_INVALID_HTTP_TOKEN]

### ISSUE THREAD

**Issue by sergyio3** [Xzandro/sw-exporter#227]
I was using exporter for a week and it worked fine and then i enable setting RunLogger and then next day this error start happening and now it happens even if i disable this setting.
![javascript error](https://user-images.githubusercontent.com/27852467/60807134-1c5ba080-a185-11e9-80f6-3d3a23447d50.png)

**Comment by Hordil** [comment]
Seems like we got https again.. And so the wave starts again!
