### ISSUE TITLE
Port in Use

### ISSUE THREAD

**Issue by claytondaley** [Xzandro/sw-exporter#229]
I know 8080 is in use.  I run Docker for Windows (using Hyper-V) and have a running container bound to 8080.  When I start SWExporter using the same port, I don't get an error in the log but the proxy doesn't work.  Switching to 8081 (unsurprisingly) works fine.  I tried enabling "debug messages" but don't see anything extra/useful.  Anything else I can provide to help troubleshoot?

**Comment by Xzandro** [comment]
Hmm, I dont really see how this is an issue with SWEX. If a port is blocked somehow, you can just switch to another one, which seems to work fine in your case. Can you clarify on what you think is a SWEX bug?

**Comment by claytondaley** [comment]
I expect SWEX to give me an error not happily state that it's "Now listening on port 8080" (which is what happens).

**Comment by Xzandro** [comment]
Normally, this check is already there: https://github.com/Xzandro/sw-exporter/blob/master/app/proxy/SWProxy.js#L110

**Comment by claytondaley** [comment]
I see.  It looks like that block would swallow any other error code.  Whether or not it helps debug my issue, you should probably add a debug message that prints other error codes.

I'll try running the code on my end with a checkpoint and see if I reach the block.
