### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by DamienStylez** [Xzandro/sw-exporter#230]
How should I setup the proxy when Android 9 doesnt support / doesnt save proxy settings?

**Comment by DamienStylez** [comment]
Edit: https://www.reddit.com/r/summonerswar/comments/ba21pf/swex_not_working_in_android_9/
THis is basically the only fixation atm - if anyone else had the same problem as i had.

**Comment by PeteAndersen** [comment]
Duplicate of #255
