### ISSUE TITLE
SwarfarmLogger: Error: invalid character in header content ["Authorization"]

### ISSUE THREAD

**Issue by Zacki78** [Xzandro/sw-exporter#232]
I installed the proxy yesterday and everything was working fine, all runs got transferred to Swarfarm.
Today after startup I get the following error message after a complete dungeon run (DB10):
Error Plugin - SwarfarmLogger
Error: Invalid character in header content ["Authorization"]

I already got a new API Key from Swarfarm, restarted the Proxy, did not help.

**Comment by PeteAndersen** [comment]
I have seen this reported a couple times but am not aware of the cause. Can you double check if there is any whitespace before or after the API key in the settings?

**Comment by PeteAndersen** [comment]
Another check would be to copy the entire API key you have in the settings (using ctrl+a, ctrl+c or cmd+a, cmd+c if mac) and paste it into https://codebeautify.org/string-hex-converter. I would need to see the output of this so you can either email it to me privately to swarfarm@porksmash.com, or just paste it here and immediately regenerate your API key on swarfarm so it becomes invalid.

**Comment by Zacki78** [comment]
It looks like there was a carriage return after the API key which caused the issue, after I removed it the plugin is working fine.

I was just wondering why it worked after the installation, but I assume that I entered the API key after I started the proxy and therefore it was not considering it until next restart

Thanks four your help on this!

**Comment by PeteAndersen** [comment]
That's correct, a restart is required before it takes effect. Something I am aiming to improve with the next release
