### ISSUE TITLE
Error code when using Exporter

### ISSUE THREAD

**Issue by EnnaelK3219** [Xzandro/sw-exporter#233]
https://gyazo.com/77644dd7f89103d055eae024b1f82681

This issue happens no matter what action I want to take in-game.  World Boss, Rift Beasts, Arena, even trying to load the game gives this error screen.

Nothing changed from yesterday when using this program, so all the settings were the same.  I don't know what happened to make this error start happening, but it never happened every time I used it until now.

**Comment by Xzandro** [comment]
Is this still a thing? I couldn't find any way to reproduce this on my machine.
