### ISSUE TITLE
Can't get any export

### ISSUE THREAD

**Issue by Bulit** [Xzandro/sw-exporter#238]
Hi

I just done every thing from help a couple of times but when i start proxy set all on my phone and then lunch SW i didnt get any export of my game data. Should i do something or what according to help it should download my data automatically. PLZ help i really want to try that to optimize my rune

**Comment by athena613b** [comment]
Mine is doing the same thing.  I changed port it's listening on.  I turned off the firewall completely when adding exporter to the firewall didn't work.  I turned off wifi and turned it back on.  It was working perfectly 2 days ago.  Just stopped today.

**Comment by Xzandro** [comment]
Duplicate of #234
