### ISSUE TITLE
[PLUGIN SUGGESTION] RTA Logger?

### ISSUE THREAD

**Issue by djluis48** [Xzandro/sw-exporter#245]
Hello!

As we all now, RTA is becoming more and more competitive each season and would be cool if we could have a way to log the data of each match and export it so it could be analized, and get better as a player.

I noticed that on the full logger, when you load the RTA Replay List, 'getRtpvpReplayList' gets called and the server responds with all the data of the last 15 matches. I think it would suffice if all that data gets sorted out and exported on an excel.

Hope someone does it!

**Comment by Xzandro** [comment]
This is probably better done as an external plugin, since SWEX supports these for a while now.
