### ISSUE TITLE
Just for my curiosity regarding to use Nox

### ISSUE THREAD

**Issue by siwakorn9** [Xzandro/sw-exporter#253]
May I have a quick question for becoming a new user of emulator (Nox)

As I have played this game so many years and spend load of time to this game.
I have stupid concern regarding to use emulator...

Can somebody please confirm with me if you have been using this emulator for awhile and being fine so far...
However, I still want to hear some negative feedback from people was getting ban.

Looking forward to hear from experience guy!

Bunch of Thanks,

**Comment by Xzandro** [comment]
This has nothing to do with SWEX. Please ask these questions on Discord or reddit.
