### ISSUE TITLE
V0.29

### ISSUE THREAD

**Issue by TonalPaladin** [Xzandro/sw-exporter#260]
Thx for the Hard Work! It works fine again...

**Comment by smcdonald45** [comment]
How? Can you provide some tipps are infos what I can do? I use android.

**Comment by Razgort** [comment]
Hello, yep more infos could be usefull because on my side it's not working : failed to login error s9

**Comment by Xzandro** [comment]
No problem.

**Comment by TonalPaladin** [comment]
okey i try it! You need to create the certificate with the swex then put the generated file to your phone! install the certificate and enable it... then use your swex normal...
