### ISSUE TITLE
Can't install SWEX

### ISSUE THREAD

**Issue by Yannus29** [Xzandro/sw-exporter#261]
Hi, i downloaded last version and wanted to try it, but when i try to start SWEX, the installation block before the half on the download bar. So i tried others versions and it's the same for all of them now... Any solution please?

**Comment by Zablan55** [comment]
Está dando erro para busca as informações

**Comment by Zablan55** [comment]
No momento de puxa os dado com o proxy ativado da o erro de rede (S9)

**Comment by Yannus29** [comment]
I just finished my system restore, and SWEX could be reinstalled. Sorry for the inconvenience.
The 0.0.29 maj does not work for me, I will try with the 0.0.27

**Comment by Zablan55** [comment]
funcionou usa o 0.27?

**Comment by cesium62** [comment]
I went to the latest release and downloaded v 0.0.29. The download page says to make sure to read reddit and discord for extra steps.  It would be kind and gentle if you wouldn't waste our time making us figure out where in reddit to look for said instructions.

**Comment by Xzandro** [comment]
Or you could be not entitled and spent 2 minutes looking this up. I spent hundred of hours making this possible and you complain about investing a few minutes? 

Just for you: look in the #243 issue. You will find everything there. Closing.
