### ISSUE TITLE
ca.pem

### ISSUE THREAD

**Issue by vinnyzudo** [Xzandro/sw-exporter#264]
Hi Xzandro, The certificate is being generated expired, always with the date of the 28th.

**Comment by Xzandro** [comment]
Its not. Look at the year, its 2029, Its valid for ten years.

**Comment by vinnyzudo** [comment]
I found the problem, if you install version 0.0.27 and generated certificate, when installed version 0.0.29 it uses the old certificate, I deleted it from AppData \ Roaming \ Summoners War Exporter and it generated a new one with the date you passed. tkz
