### ISSUE TITLE
Even after steps I cant login to game when using proxy

### ISSUE THREAD

**Issue by bugz0r** [Xzandro/sw-exporter#265]
I read the steps and completed them on my OnePlus 3T (android 9)

I ran the ca.pem from cert and connected the wifi trough the appropriate proxy and port (like i used to to for a long time when it did work)

I get this error, cannot connect to ..  

If my android version is too new... so my android version is the problem.. is there any way around?
Maybe in the cloud or something?

I could really use  SW exporter to work :S

**Comment by Xzandro** [comment]
You didnt read it carefully enough it seems. Its clearly states that it doesnt work for Android 7+

**Comment by bugz0r** [comment]
Thanks for the reply,

I read it, but still gave it a try.

Any workaround at the moment?

Are you working / trying to fit the issue?(of course created by c2u)

Op do 29 aug. 2019 om 20:39 schreef Xzandro <notifications@github.com>:

**Comment by Xzandro** [comment]
No. You have to use an older device, an iOS device or an emulator.

**Comment by bugz0r** [comment]
Hi,
I found an ihphone but after altering the wifi it gives the same error.
Any idea what i am doing wrong?
Its ios12

Op vr 30 aug. 2019 13:43 schreef Xzandro <notifications@github.com>:

**Comment by bugz0r** [comment]
Found it!!

Thats for the Quick responses and the great worm.

Op vr 30 aug. 2019 20:28 schreef M H <kontkontin@gmail.com>:

**Comment by Xzandro** [comment]
Closing.
