### ISSUE TITLE
[BUG] After upgrading to the latest version can't connect with the network

### ISSUE THREAD

**Issue by Sinnersslayer** [Xzandro/sw-exporter#267]
**Describe the bug**
As in topic. After upgrading to the latest version getting a pop up in game, that it can't connect with the network.
Have tried to conect with the other game, same result. Getting connection problems.
But internet connection is working after connecting through the proxy. 

**Smartphone (please complete the following information):**
 - Device: Galaxy S10e
 - OS: Android

**Comment by Xzandro** [comment]
The Android version of the Samsung S10e is probalby over 6 so this will not work out. Please inform yourself about the limitations here: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/

**Comment by Sinnersslayer** [comment]
But on my previous phone, the Galaxy S8 it worked just fine on Android 9

**Comment by Xzandro** [comment]
A lot of things changed during the last 2 weeks. Please just read the thread.

**Comment by Sinnersslayer** [comment]
So it means I can't use it anymore unless I root my phone?

**Comment by Sinnersslayer** [comment]
I've tried to do it as in the thread for BlueStacks.
Now when I'm trying to launch the game after rooting the game shows me network same network connection error as on the phone.
Guess I'll just pass on SWEX.
RIP
