### ISSUE TITLE
Erro ao puxar dados do celular[BUG]

### ISSUE THREAD

**Issue by Zablan55** [Xzandro/sw-exporter#269]
Com proxy ativado, no celular da erro de rede (S9) não puxando dados para o programa.
Somente eu com este problema?

**Comment by Xzandro** [comment]
Read this thread please: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/

Also, this repo is pretty much English only.
