### ISSUE TITLE
[BUG] New SW patch make the exporter not working

### ISSUE THREAD

**Issue by erdosam** [Xzandro/sw-exporter#272]
I've tried several "tips" but cant get it work on Samsung A50.
Two version of SWX has been tried.

**0.0.22**
- The proxy seems OK, but can't get the data. SW is connected to network when the proxy is ON, but no log whatsoever.

**0.0.30**
- Now, when the proxy ON, SW cannot even connect to the network.

**Comment by Xzandro** [comment]
Please read: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/
