### ISSUE TITLE
[BUG] SOLVED Proxy stops working after running for a while

### ISSUE THREAD

**Issue by hyudryu** [Xzandro/sw-exporter#273]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cnwaq5/swex_0027_attempt_to_restore_export_functionality/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
The bug occurs after SWEX has been running for a while, and it stops logging runs, exporting profiles, etc. 

When SWEX is first opened, clicking the stop/start proxy will give a feedback of "Proxy stopped"/"Now listening on port 8080". 
![image](https://user-images.githubusercontent.com/22283864/64095077-a4d46880-cd12-11e9-8ffc-d5cfe0a76fe2.png)
After a while, I noticed that the proxy would stop exporting json files. And at the same time, clicking the stop/start proxy would give zero feedback as if the software is hanging. (However, I can still play the game as usual, so the proxy is still passing information through it, just not logging it)

**To Reproduce**
There doesn't seem to be an exact way to reproduce it, since it's kind of unpredictable. However, through my testing, I have been able to reproduce it **within 10 minutes**.

Every time I power up a rune, it creates a "live" json file, and after powering up/selling many runes, it would sometimes cause the proxy to bug and stop exporting anything. It took around 134 "live" json exports before the proxy stopped responding. When the proxy does stop responding, clicking the start proxy/stop proxy button will not do anything.

**Expected behavior**
The proxy stops exporting runs/profiles/runes

**Screenshots**

![image](https://user-images.githubusercontent.com/22283864/64093779-7ce30600-cd0e-11e9-839b-2198d65b1ebe.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Version v0.0.30

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone XR
 - OS: [e.g. iOS8.1] 12.4 jailbroken

**Additional context**

**Comment by Chrysadelic** [comment]
I have the same problem. After around 2 hrs., the exporter v0.0.30 stops logging for me as well.

**Comment by hyudryu** [comment]
Found the issue, to anyone who has the same issue:
![image](https://user-images.githubusercontent.com/22283864/64903334-65d7d880-d66b-11e9-9d22-c1ce2c3c3342.png)

**Comment by Xzandro** [comment]
Duplicate of #223
