### ISSUE TITLE
Loading errors

### ISSUE THREAD

**Issue by varyalitszia** [Xzandro/sw-exporter#274]
I have issue since 0.0.27,  so i already used it before but now when i use it i have connection issue s:9 or a loading errors, in both case i have no logs, i have try to switch the port, and to modify the firewall, but seems like i can't have any access with the proxy.
Before this i never had any issue, i am on android 7.0.

**Comment by Jasnik16** [comment]
Same Problem here!!
I´m using Windows 10 and a Samsung Galaxy S9+ (Android 9) with SWExporter and i get the same problem as mentioned before from varyalitszia.

**Comment by Xzandro** [comment]
Please read: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/
