### ISSUE TITLE
[BUG] Can't contecting to server

### ISSUE THREAD

**Issue by MrAnhKieu** [Xzandro/sw-exporter#275]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cnwaq5/swex_0027_attempt_to_restore_export_functionality/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Screenshots**
![IMG_11069B4C96D2-1](https://user-images.githubusercontent.com/21331513/64149523-4c0aea00-ce50-11e9-8547-7208d14aca9b.jpeg)
<img width="958" alt="Screen Shot 2019-09-03 at 1 36 06 PM" src="https://user-images.githubusercontent.com/21331513/64149602-7d83b580-ce50-11e9-9369-b725c3d720aa.png">
![IMG_11069B4C96D2-1](https://user-images.githubusercontent.com/21331513/64149645-9db37480-ce50-11e9-824b-cbe7eb4176dc.jpeg)

**Desktop (please complete the following information):**
 - OS: macOS [e.g. iOS]
 - Version: Mojave 10.14.6

**Smartphone (please complete the following information):**
 - Device: iPhone7 
 - OS: iOS12.0

**Additional context**
In case, I used Safari to browse the web when connecting to the proxy -> OK

**Comment by Xzandro** [comment]
This usually means you forgot to trust the cert after installing it, like described in the reddit thread here: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/

**Comment by MrAnhKieu** [comment]
It worked! Thank alot!!!
