### ISSUE TITLE
SW unable to connect over SWEX proxy on all mobile OS

### ISSUE THREAD

**Issue by Majinthew** [Xzandro/sw-exporter#276]
Posting this on here since no one responds to me on reddit:
When connecting to proxy through SWEX, Summoners War gives me an error code:
Failed to connect with the network. Please try again later. (S:9)
I've tried with current android and ios as well as android 7 on bluestacks. Same thing every time. 
I love this tool and would love to keep supporting it if it wasn't so complicated to connect to as I can't find any work-around for this issue. I figure it is something on SW's end that doesn't allow it to connect over proxy, but I keep seeing other people continue using it, so idk what to do. 

[EDIT]
I used the "bluestacks fix" and rooted it and everything. Finally it connects but no .json file is generated.

**Comment by RoBeach17** [comment]
Yeah man i had the same issue,and i'm looking for a fix for few days ago,i'm sad because i wanted to rune some monsters with the frr. ;(

**Comment by riotape** [comment]
I thought i was the only one with this problem.. I created an account just so i could comment as well. I hope this gets fixed. I rely heavily on the SWOP tool. I can't move around my runes anymore.. :(

**Comment by DanielMarshall** [comment]
Same problem here, apple tablet, latest version of the OS (It auto updated a day or 2 ago, but this issue has been around for the last month or more for me)

**Comment by Xzandro** [comment]
Everything you need to know: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/?utm_source=share&utm_medium=web2x
