### ISSUE TITLE
SW Exporter generate s:9 error in Summoner Login 

### ISSUE THREAD

**Issue by vitolioce** [Xzandro/sw-exporter#277]
After I activate the proxy, when I try to load and log in SW, the game send me this error. 
After I shut down the exporter (or stop the proxy), the game works normally. 
The version I used il the 0.0.30

![Screenshot_20190908-005332](https://user-images.githubusercontent.com/5405384/64480958-2e80ac00-d1d3-11e9-9432-3b78d3718ca0.png)

I take this opportunity to thank you for all the work you have done.

**Comment by jcp171** [comment]
I have the same issue trying to run Summoner's war on iPad with Summoners War Exporter running on Windows 10 OS PC. I have downloaded and imported the certificate on the windows side, but I am pretty sure it is needed on the iOS side and I have been stumped as to how to accomplish that.

**Comment by Jeppertt** [comment]
i have the same issue on android version 9 on samsung s10+, any fixes?

**Comment by vitolioce** [comment]
Also my issue is on an Android Phone (Samsung Galasy S6 Edge) with a Windows 10 PC

**Comment by alferreira1990** [comment]
same here
i set the proxy, save it, then i runned the proxy and i allways get this S:9 error code, that i think its without internet connection, but my phone has wifi

**Comment by PeteAndersen** [comment]
Have you all read and understood the information here: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/ ?

**Comment by jcp171** [comment]
I did finally get it working. I was using an old version of your certificate. Did not realize it changed. Thanks!

Thanks,
Joe

On Sep 9, 2019, at 4:46 PM, Peter Andersen <notifications@github.com> wrote:

Have you all read and understood the information here: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/ ?
