### ISSUE TITLE
Provide a Linux build

### ISSUE THREAD

**Issue by PGPereira** [Xzandro/sw-exporter#28]
For the linux users out there.

**Comment by Xzandro** [comment]
Thats defintely planned. Very soon! It already runs on linux if you run it from source.

**Comment by PGPereira** [comment]
How I do that?

**Comment by Jbag1489** [comment]
On the Readme.md file, follow those steps and it will run

**Comment by Jbag1489** [comment]
git clone https://github.com/Xzandro/sw-exporter.git
$ npm install
$ npm run dev
$ npm start


On Apr 6, 2017 8:21 PM, "Josh Bagwell" <jbag1489@gmail.com> wrote:

On the Readme.md file, follow those steps and it will run

**Comment by Xzandro** [comment]
And you would need to install node.js too. Maybe I can package a .deb / .rpm linux file tomorrow.

**Comment by PGPereira** [comment]
I could get it to work, many thanks for your good working.

**Comment by sr972** [comment]
To be honest, a linux user should be able to handle this via npm w/o furter debs or rpms as it is a simple npm.

And it's way more easier to handle w/o an additional repo to handle or always use the packagemanager.

-1

**Comment by Xzandro** [comment]
As of the newest version 0.0.17 we provide a linux package too.
