### ISSUE TITLE
[ERROR] "HIVE login server connection failed. Please try again later (H:2000)"

### ISSUE THREAD

**Issue by biulanar** [Xzandro/sw-exporter#281]
Hi.

HIVE login server connection failed. Please try again later (H:2000)

Already turned off all my firewalls.
Enabled port 8080 on router.
Checkd 1000 times my ip and port on phone.
Activated the cert on phone. (android)
Windows10 user

Nothing works....

**Comment by Xzandro** [comment]
Please read https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/
