### ISSUE TITLE
SWEX version 0.0.30 

### ISSUE THREAD

**Issue by Xaan2000** [Xzandro/sw-exporter#282]
I have followed the instructions to the letter from reddit on how to get version 0.0.30 working,  I have been able to install the CERT on my phone (iphone xsmax),  I have installed the SWEX 0.0.30 on my Windows 10 machine.  I have set the manual proxy settings.  Everytime I attempt to log in, I get an S:9 error on my phone and it will not continue to log in.

I appreciate all the work that has gone into this application.  Thank you in advance your your assistance with this.  Has anyone else run into this problem or found a way to correct it?

**Comment by Xzandro** [comment]
Usually people forget to trust the cert after installing it in iOS. It's also described in the steps.

**Comment by dreamster55** [comment]
Have the same exact error and I trusted the cert and everything.

**Comment by Xaan2000** [comment]
I did check that the cert was trusted.  I also check that the wifi was on and that both devices were on the same wifi. I also made sure that SW was not running while I corrected the manual proxy settings.  Is there some other piece of data that I can provide that would be helpful?

**Comment by 911dummy** [comment]
I am having the exact same issue on an iPhone 8, and iPhone X. I've redownloaded the proxy twice, done the certs 3 times, trusting them each time.

**Comment by Xzandro** [comment]
No idea honestly. Everyone who contacted me via Discord did something wrong regarding iOS. Worked 100% of the time pretty much. Hard to say honestly. Might wanna join my Discord to to troubleshoot this more easily: https://discord.gg/JMBSZRA

**Comment by 911dummy** [comment]
Well, it worked before, and I tried 6 times to get it to work. It worked on
the 6th time. Go figure.

**Comment by Xzandro** [comment]
Closing. There is currently no general bug related to iOS. Even iOS13 works fine if you use SWEX 0.0.30 and follow all the steps. If you used previous versions you have to wipe out the cert once. Her eis how you do it:

First close SWEX. Then you need to clear out the previous certs. They are located in C:\Users_USER_\AppData\Roaming\Summoners War Exporter\swcerts Clear out this folder. Start SWEX 0.0.30. Do all the steps again.

Again: please read this carefully, epsecially the cert path.
