### ISSUE TITLE
[BUG] SWEX not working on ios 13+

### ISSUE THREAD

**Issue by bart6446** [Xzandro/sw-exporter#283]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
SWEX 0.0.30 worked perfectly on ios 12.x with the certificate. After I've updated to ios 13.0 and 13.1, they both have connections issues when I start summoners war. I've deleted the whole certificate folder and deleted the profile on my iPhone X, created, installed and trusted a newly generated certificate.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image0](https://user-images.githubusercontent.com/55766987/65550890-de1e8380-df20-11e9-8c2a-54037e56f83a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - 10

**Smartphone (please complete the following information):**
 - Device: iPhone x
 - OS: IOS 13.0 and 13.1

**Additional context**

**Comment by Xzandro** [comment]
Did you use other versions like 0.0.27 or 0.0.29 before v30? If thats the case you have to wipe out the certs completely and generate a new one, since iOS requires a more secure certificate.

Please follow these instructions: 
First close SWEX. Then you need to clear out the previous certs. They are located in C:\Users\__USER__\AppData\Roaming\Summoners War Exporter\swcerts Clear out this folder. Start SWEX 0.0.30. Do all the steps again.

**Comment by bart6446** [comment]
Yeah, i've closed swex, deleted the whole cert folder, started swex again, pressed get cert, deleted the old cert on my iPhone, installed the new one and i still get this error. 
i've indeed used 0.0.27 AND 0.0.29, after updating from 0.0.27 to 0.0.29 and from 0.0.29 to 0.0.30 I did the steps with deleting the old cert and it all worked great. but since i updated to Ios 13.0 it doesn't work anymore. I waited till the ios 13.1 release today before opening an issue because ios 13.0 had some mild bugs. but even on ios 13.1 i cant get it to work. My ipad that's on ios 12.4.1 still works great.

**Comment by Xzandro** [comment]
Are you sure you did all the described steps? That should definitely solve this. I had the same case yesterday with iOS 13 and it worked perfectly fine after the steps I stated above.

**Comment by bart6446** [comment]
im going to try again and describe all my steps now;
1. close swex
2. delete cert folder
3. restart pc
4. deleted "sw-exporter-setup-0.0.30.exe"
5. downloaded "sw-exporter-setup-0.0.30.exe"
6. start SWEX
7. pressed "get cert"
8. delete cert on iPhone
9. restart iPhone
10. send cert to iPhone through e-mail
11. download cert from mail
12. installed profile(cert)
13. trusted root cert
14. set proxy to manual and entered the correct ip and port(I configured a static ip to my PC with my MAC-Adress so a wrong ip-adres can't be the issue)
15. started summoners war and still got the error

**Comment by Xzandro** [comment]
Can you specifiy the cert folder location you deleted? It's not the one SWEX copies to. Its an internal folder, which was the reason I stated it in detail above.

**Comment by bart6446** [comment]
I'm so sorry, I indeed deleted the wrong cert folder, didn't read correctly. Thanks for the quick response and help! and thanks for all the work you've put into this tool!

**Comment by ios-user-1-2-3** [comment]
Remember to do the certificate trust settings radio button after installing the new pem file to iOS

**Comment by deirdresm** [comment]
I read all these and found I had a different problem, so here's my solution.

My network is split into two: 2.4 and 5 GHz, but only one of them had the proxy set up for it. Naturally, I wasn't using the same selection on both wifi menus and thus had problems connecting. So if you have one router/whatever that splits into two wifi networks, make sure you're using the same selection for network on both ends.

**Comment by Petchou91** [comment]
@Xzandro Why don't  you just post a complete tutorial on youtube and put a link to it into SWEX ? (Like one video or web page -with screenshots- for each kind of device, such as iOS, Nox, BlueStacks, Android, etc (even if I thinks that's all)
I wouldn't take too much time (I'm sure that someone could do that for you) and it could help a lot the most user who have difficulties to get their json data file.


Anyway, thank you for your work, it is so helpful for the whole SW community !!! Keep on that way !

Maybe see you soon in the arena (;
Petchou91

**Comment by Xzandro** [comment]
Feel free to do a PR. This is open source, so the goal is that I dont even have to do anything. I usually have evry limited time.
