### ISSUE TITLE
[BUG] SWEX not working

### ISSUE THREAD

**Issue by joeccyin** [Xzandro/sw-exporter#284]
I'm using iOS 13.1, iPhone 6s, iPhone XS and iPad also not working.

**Comment by BadUncle23** [comment]
I can confirm it no longer works on the new Ipad OS.

**Comment by joeccyin** [comment]
Thank you for you reply!

It work prefect last month, I will use android device to try tomorrow, hope
it can work on new iOS later.

Kind regards,
Joe

「BadUncle23 <notifications@github.com>」在 2019年9月30日 週一，上午12:58 寫道：

**Comment by Xzandro** [comment]
Duplicate of #283
