### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by davidezocca** [Xzandro/sw-exporter#285]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
Proxy connection problem

**To Reproduce**
1. Set up the proxy
2. Open Summoner Wars app V 5.1.1
3. Get error "HIVE login server connection failed. Please try again later.(H:2000)"

**Expected behavior**
The proxy is set up correctly for the browser, but it seems to be blocked for Summoner wars app

**Desktop (please complete the following information):**
 - Windows 10
 - Version 10.0.17763 

**Smartphone (please complete the following information):**
 - Device: Moto Z play
 - Android 8.0.0

**Additional context**
The connection worked until 2 months ago. The phone, SW app and SW exporter got updated and now the proxy connection doesn't work

**Comment by Xzandro** [comment]
SWEX doesn't work with unrooted Android 7+ anymore after the com2us changes. See [this thread](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/)
