### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RobinHashGreen** [Xzandro/sw-exporter#288]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
i get an error message when trying to use SWEX with summoners war. Wont allow me to enter and play the game unless i remove the proxy.

**To Reproduce**
1. i used SWEX as I'm suppose to, i.e. plug in the proxy for _host name_ and _port_ and open the game.
2. pressed on "Get Cert"
2. Started the proxy.
3. Opened up summoners war to start the extraction.
4. Summoners war gives error message at start up screen and doesn't allow me in enter unless i exit the proxy.

**Expected behavior**
cant play the game unless proxy is removed.

**Screenshots**
![Screenshot_20191005_163303](https://user-images.githubusercontent.com/56190449/66253299-4c204180-e790-11e9-9e4a-18585edae03e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 1809
 - OS build: 17763.737

**Smartphone (please complete the following information):**
 - Device: VIVO S1
 - OS: FuntouchOS_9

**Additional context**
Sorry if i haven't provided enough information. 
im using Kernel version:  4.14.94+ 
Andriod version: 9

**Comment by davidrama** [comment]
Same issue on IOS 13.1.1 - iPhone Xr
Desktop: MBP OSX 10.14.6

**Comment by Esthean** [comment]
Same issue, IPhone 7

**Comment by shironguyen** [comment]
same with Iphone XS Max 
MBP OSXOSX 10.14.6

**Comment by Xzandro** [comment]
@RobinHashGreen Android 8 isn't supported. Which is stated in the link above.

For all the iOS users: I recommend reading this issue: https://github.com/Xzandro/sw-exporter/issues/283

All in all, everything is written in the SWEX mega thread: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/
