### ISSUE TITLE
[BUG] Followed every tutorial but still doesn't work

### ISSUE THREAD

**Issue by Tdogz** [Xzandro/sw-exporter#289]
I have done and checked every single step and tried every tutorial but i cant import my runes. I don't know if anybody else has this issue but it is very frustrating. I put the port and server proxy name in the WiFi settings on my iPhone but when on summoners war, i get the message "Failed to connect with the network. Please try again later."

**Comment by Xzandro** [comment]
Please use this thread: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/

There are no known other general issues other than what's written in the limitations section.
