### ISSUE TITLE
ios 13 update, SWEX not working now [BUG]

### ISSUE THREAD

**Issue by ios-user-1-2-3** [Xzandro/sw-exporter#291]
after updating to ios 13, SWEX is no longer working.  Error states failed to connect with the network.  Attempted to reinstall the cert and swex, still received the same error.

**Comment by Xzandro** [comment]
It is still working.
Duplicate of #283

**Comment by ios-user-1-2-3** [comment]
Remember to do the certificate trust settings radio button after installing the new pem file to iOS
