### ISSUE TITLE
SW fails starting after update [macos]

### ISSUE THREAD

**Issue by MircoBlitz** [Xzandro/sw-exporter#294]
Hi, I use SWEX for a while now and got worked flawless on my Macbook with my Ipad using the SWEX Proxy. After updating SW and SWEX to latest Version on Monday, I get "Failed to connect with the network. Please try again later. (s:9)" in SW. When using safari, I get every site I look for and if I deactivate the proxy, safari will not connect anymore, so the proxy itself is working. The network error only appears in SW. It's a bummer that the debug does not show the requests and responses. That would help to find the issue. I also tried to install the MIT cert new, wich did not change anything. (I dont think that changed).

Can you help me solving this please?

**Comment by Xzandro** [comment]
Might also be related to #283 
It probably is more related to the update to iOS 13.

**Comment by MircoBlitz** [comment]
That can not be, because I am on 12

**Comment by MircoBlitz** [comment]
And can you please tell where this ominouse cert directory should be on mac? Your link to the other issue does not help!

**Comment by Xzandro** [comment]
SWEX Settings -> Settings Path. Might be hidden by default. Its either that or you didn't trust the cert.

**Comment by MircoBlitz** [comment]
Ok I cleaned that multiple times and tired again, it persists.

**Comment by Xzandro** [comment]
Then you didn't install AND trust the new cert correctly after doing so.

**Comment by MircoBlitz** [comment]
I did

**Comment by MircoBlitz** [comment]
I did everything fresh 3 times all over including installing, deleting all folders and reinstalling sw (huge with my connection)

**Comment by Xzandro** [comment]
Highly doubt it. I get this error (s:9) pretty much every day in combination with iOS devices and every single one of them was solved after dong these steps.

**Comment by MircoBlitz** [comment]
I can try again. Will tell in 10

**Comment by MircoBlitz** [comment]
I removed the folders
/Users/lindworm/Desktop/Summoners War Exporter Files
/Users/lindworm/Library/Application Support/Summoners War Exporter

restarted SWEX0.0.31
started the proxy
copied the ca.cert to new icloud drive folder

in ios:
went to settings -> general -> profiles and deleted the "old" one
opened iCloud drive folder and tapped ca.pem
went to settings -> general -> profiles and installed the new one

Problem persists as described

**Comment by Xzandro** [comment]
I dont see the trusting step. You only installed it it seems. Did you trust the cert?

**Comment by MircoBlitz** [comment]
What trusting step? It asked me twice If its ok to install and the Certificate shows verrified. I don't see anything where i should trust.

**Comment by MircoBlitz** [comment]
It's also kind of hard to figure the certificate part out by oneself. I don't see a description of it anywhere and somehow it worked the first time around, where i fiddled with the cert as well.

**Comment by Xzandro** [comment]
Well, you probably didn't read the thread correctly. Which is the exact reason why I close these thread this fast. If you create a bug report there even is the thread AND the Discord server linked on top. Bug reports are for general bugs with SWEX and not user errors or misunderstandings. I don't have an iOS device but it should be.
 settings -> general or about-> certificate trust settings -> then toggle radio button on -> continue

**Comment by MircoBlitz** [comment]
Not everybody has discord! If it is a common problem, why is this essential step not in the help section, but you say in readme that everything you need to know stands there ¯\_(ツ)_/¯? Isn't then to be expected that users bug you with that question? None the less I would not do that to my users, I consider it rude and unfriendly, even if the come up with dumb questions.

**Comment by MircoBlitz** [comment]
Thank you.

**Comment by Xzandro** [comment]
It isn't rude. It needs to be done to keep an order in this repository. Easy as that. There is also a [mega thread](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/) on reddit. As I said, this is also written if you try to create a bug report in bold on top.
Anyway, glad it worked out.
