### ISSUE TITLE
[BUG]A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Addi1199** [Xzandro/sw-exporter#297]
When starting swex i get the error message as seen in the screenshot. I think that my swex doesnt work in general since it wont export the json file even though I installed the certificate. Also when i first start the donwloaded swex.exe the windows defender smartscreen tries to block the app. Maybe thats the reason the error occurs. The error occurs as far as i can tell on all releases.
![Swex_Error](https://user-images.githubusercontent.com/56731276/67104125-b55b7800-f1c6-11e9-9aef-1bdceac7a090.png)

The os is win 10 and since the exporter doesn't work on my iphone 5c aswell as on nox i don't think that the device is the problem.

**Comment by Xzandro** [comment]
Hi. You are not using SWEX. You are using SWproxy, which is outdated and deprecated and also not working anymore.

**Comment by Addi1199** [comment]
Nah im using swex its just in the folder of swproxy

**Comment by Xzandro** [comment]
There is no BarionEfficiencyPlugin in SWEX, so this error doesn't make any sense regarding SWEX.

**Comment by Addi1199** [comment]
well this is what happens when i just download swex so idk whats happening. should i change the files path?

**Comment by Xzandro** [comment]
As i said. You are definitely NOT using SWEX. This error is a python error. SWEX is written in Javascript. SoI'm not sure, what you are doing honestly. Also not sure what you downloaded. SWEX is only one exe and that's it.

**Comment by Addi1199** [comment]
just changed the files paht and that seems to solve the problem. as i said I AM using swex. I think it might have tried to run some files from swproxy that still were in the same folder. Sry for bothering you since this was clearly a user error out of lazyness ^^'
