### ISSUE TITLE
[BUG] error : net::ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by MrSuricate2** [Xzandro/sw-exporter#298]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
I can not connect to the game and extract the .json from my account

**To Reproduce**
1. I opened SW-export
2. I started the proxy
3. In my wifi setting I copy the ip and the port given by sw-export
4. I open summoners wars and I have the error: error : net::ERR_PROXY_CONNECTION_FAILED

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 1903

**Smartphone (please complete the following information):**
 - Device: oneplus 6T
 - OS: oxygene OS == android 9.0

**Additional context**
I have the same problem on my computer under ubuntu

**Comment by Xzandro** [comment]
As you can read in the thread on reddit, which is stated on top of the bug report. This does not work for unrooted Android 7+ phones.
