### ISSUE TITLE
Forced Update Loop

### ISSUE THREAD

**Issue by rogersmi87** [Xzandro/sw-exporter#30]
When I try to use the exporter, summoners war says that  "an update to the latest version is required. 

My file is fully updated. 

When I turn off the proxy, I can use summoners war fine.

**Comment by AizenSousuke** [comment]
Is this on 14 or 12 version?

**Comment by rogersmi87** [comment]
This is on 14

**Comment by Xzandro** [comment]
That seems more of a general problem. SWEX doesnt really have anything to do with with downloading updates etc. I cant reproduce this either. I leave it open, maybe you (or someone else) can gaher more information.
