### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bomber604** [Xzandro/sw-exporter#302]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
Once connected through the correct IP and Port, on login attempt you receive HIVE login server connection failed. Please try again later (H:2000)

**To Reproduce**
1. Go to Summoners War Exporter
2. Click on Start Proxy, then Get Cert
3. Open Summoners War on Phone

**Expected behavior**
Login to Summoners War account and start loading Logs into Summoners War Exporter

**Screenshots**
Screen Shot of error attached. Connection to Wireless Router shown.
![SW login attempt Screenshot (Nov 13, 2019 11_18_05 PM)](https://user-images.githubusercontent.com/49049152/68828679-29752880-066c-11ea-824f-715833967982.png)
 

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 10 Home

**Smartphone (please complete the following information):**
 - Device: Razer 2
 - OS: Android 9

**Additional context*
The last time I used Summoners War Exporter was Version 0.0.23. I just downloaded the newest version to try and update my SWFarm account and couldn't get it to work. I have been looking through the new instructions and have not found what I need to resolve this issue. Thank you for your time.

**Comment by Xzandro** [comment]
Not a bug. SWEX requires additional steps, which you can read in bold in your own bug report on top.

**Comment by Casency** [comment]
old topic Xza, before covid also, but would be pleased to have your help on h:2000 as stucked with that and so ready to contrib to your beautifull work on swex
