### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zchalkerr** [Xzandro/sw-exporter#304]
i put IP and port, internet works OK.

but when i open summoners wars, give me a connection problem.

anyone?

**Comment by Randsanity** [comment]
Me too.
"Failed to connect with the network. Please try again later. (S:9)"

**Comment by Xzandro** [comment]
THis is not a general error with SWEX. Please use [this reddit thread](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/) or for additional information / help [this Discord](https://discord.gg/JMBSZRA).
