### ISSUE TITLE
Self-signed certificate doesn't work on iOS/iPadOS 13

### ISSUE THREAD

**Issue by fori920** [Xzandro/sw-exporter#307]
**Describe the bug**
Generated self-signed certificate doesn't work as expected when installing it and enabling full trust in iOS 13.

**To Reproduce**
1. Install and/or run Summoners War Exporter 0.0.31
2. Click on 'Get Cert'
3. Configure and enable the proxy.
4. Transfer a certificate copy to the target iOS/iPadOS device running 13.0 or later.
5. Install the certificate.
6. Enable the certificate following the steps below:
https://www.reddit.com/r/summonerswar/comments/cnwaq5/swex_0027_attempt_to_restore_export_functionality/ewedxpi/

**Expected behavior**
Summoners War works as expected and user data can be read/seen on the logs.

**Screenshots**
https://drive.google.com/file/d/14f7FvOzwn9dHbrMSc7bJqvwokKQpEIG8/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1903 (Build 18632.535)

**Smartphone (please complete the following information):**
 - Device: iPad 7th generation (2019)
 - OS: iPad OS 13.3

**Additional context**
The problem seems to be the certificate being generated. I tried to delete and re-generate it again, but it doesn't work anyway.

Also, the problem seems to be iOS itself, but I'm still not sure about that.
https://apple.stackexchange.com/a/371757

**Comment by Xzandro** [comment]
It does work. But you have to clear the old cert generated by older versions of SWEX before once. You can read about it in the megathread: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/

**Comment by fori920** [comment]
Yeah, I didn't clear the old certs before. Thank you.
