### ISSUE TITLE
SWEX Web + iPhone 13.3 = Error (S:9)

### ISSUE THREAD

**Issue by andre67** [Xzandro/sw-exporter#308]
Hi,
I have an issue with **SWEX Web**:
Errorcode S:9 / S9 (Network connection failed.) 
Steps I made:
1. Logged in via Patreon on swex.swop.one
2. Downloaded "Cert" via iPhone Safari Browser and installed it on the device.
3. Activated the profile as mentioned on reddit, in 'Settings' -> 'General' -> 'Info' -> scroll down 'Certificate' -> Radio Button On (Link [here](https://www.reddit.com/r/summonerswar/comments/cnwaq5/swex_0027_attempt_to_restore_export_functionality/ewefwm8/) )
4.  Clicked "Unlock" on swex.swop.one
5. Activated / Setup Proxy on my phone (with and without username)
6. Tried to start SW, Error S:9

With Proxy on Internet works fine, but why SW wont start? With SWEX Web you do not need an additional PC or Programm, am I right? 
Please help...

**Comment by Xzandro** [comment]
This repository is for the SWEX app only. SWEX Web is currently also not working. You need to use the normal SWEX app and it will work in all iOS versions.
