### ISSUE TITLE
Uncaught Exception Error any time a store purchase is made.

### ISSUE THREAD

**Issue by omar5687** [Xzandro/sw-exporter#31]
![untitled](https://cloud.githubusercontent.com/assets/6887423/24826013/2a148554-1bf2-11e7-9449-ad62bea47e1e.png)
I get this error everytime a store purchase is made, mainly my energy refills.

**Comment by Xzandro** [comment]
Please update to the newest version and make sure, that you always use the newest version before you open an issue. :)

**Comment by omar5687** [comment]
Sorry I grabbed it right before this new release came out!  Thanks for the work love the program, so much better than your predecessors.
