### ISSUE TITLE
Connection/No JSON file created[BUG]

### ISSUE THREAD

**Issue by shatgamer80** [Xzandro/sw-exporter#310]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
I fail to connect when starting SW.

**To Reproduce**
1. Got new cert (cleared old appdata swcert folder)
2. Installed on mobile device
3. Started proxy and set wifi settings
4. Started SW and got "Failed to connect with the network. Please try again later.(S:9)"

**Expected behavior**
SW would start and json file to be created

**Desktop (please complete the following information):**
 - OS: [Win 10]

**Smartphone (please complete the following information):**
 - Device: [iPhone11]
 - OS: [e.g. iOS13.3]

**Comment by jonny-khattar** [comment]
Have you been able to solve this issue? I am having the same problem

**Comment by Xzandro** [comment]
If this is about the S:9 error, it means you didn't instal lthe cert correctly. Make soure you installed AND trusted the cert. You can read more about it in the [SWEX megathread](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/)
