### ISSUE TITLE
[BUG] Cert Not Generated (Versions Above 0.0.29)

### ISSUE THREAD

**Issue by Kheran** [Xzandro/sw-exporter#311]
Using the most recent versions--0.0.30 and 0.0.31--when I click get cert, it says the expected, "Certificate copied to C:\Users\ . . ." However, when I open that folder, there is no file there.
I was able to get the cert and get my JSON using version 0.0.29. However, that version is causing an error in SWOP, as it does not recognize the Gargoyle family of monsters.

**Comment by Xzandro** [comment]
Is this still an issue? I cant reproduce this and the code wasn't changed I think.

**Comment by Kheran** [comment]
No, it is not. I uninstalled and reinstalled the most recent release (Updated nine days ago), and it worked this time.
