### ISSUE TITLE
Plugin updates needed for BattleDungeonResult_V2 command

### ISSUE THREAD

**Issue by PeteAndersen** [Xzandro/sw-exporter#312]
Game patch 5.2.7 replaced the BattleDungeonResult command with a _V2 command with a different reward layout. Sample runs available in my repo: https://github.com/PeteAndersen/swarfarm/tree/master/data_log/tests/game_api_data/BattleDungeonResult_V2

Plugins which use this command:

* rune-drop-efficiency.js
* run-logger.js
* live-sync.js

**Comment by Xzandro** [comment]
Progress in here: https://github.com/Xzandro/sw-exporter/tree/BattleDungeonResult_V2
