### ISSUE TITLE
[BUG] No internet connection ingame after manually changing proxy

### ISSUE THREAD

**Issue by matasass1346** [Xzandro/sw-exporter#313]
**Describe the bug**
When I'm changing my Wi-Fi settings to the IP and port that the SWEX shows, I can't connect to the game, which I had in the past (a year ago), but i still have internet connection.

**To Reproduce**
1. Go to Wi-Fi
2. Click on the current Wi-Fi I'm using
3. Scroll down to advance settings and changing the proxy settings
4. See error after starting the game with the new settings

**Expected behavior**
connect to the game after the new proxy settings

**Screenshots**
![Screenshot_20200320-233123_Summoners_War 1](https://user-images.githubusercontent.com/62448396/77208054-9cebe280-6b03-11ea-9726-6f75848e70aa.jpg)

**Desktop (please complete the following information):**
Windows 10 Home 64bit

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 9
 - OS: Android 10

**Additional context**
I've tried using Bluestacks and Nox with the new guide on reddit, but it doesn't work in any of them.

**Comment by Xzandro** [comment]
This is usually caused by some kind of security software. Keep also in mind that SWEX will not work for Android 7+ devices, as you can read here: [SWEX megathread](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/)
