### ISSUE TITLE
[BUG] cannot export after update sw

### ISSUE THREAD

**Issue by godshades** [Xzandro/sw-exporter#317]
Hi after update sw, I cant export profile, before it's running very well
![image](https://user-images.githubusercontent.com/12244851/77822847-eef6be80-7128-11ea-8b3d-3dec1b4f5974.png)

**Comment by Xzandro** [comment]
Please read the log. It should fix itself eventually and we cant do anything about it, since com2us just doesn't provide needed data sometimes.
