### ISSUE TITLE
Cant open the exporter

### ISSUE THREAD

**Issue by Ollie102** [Xzandro/sw-exporter#319]
Hi,  I have downloaded the zip file to my mac and unzipped it.  There is then no way for me to open the exporter proxie.  I am not sure if i am missing something.  I have opened the created folder and clicked on all of the files inside but none work.  Thanks in advance

**Comment by Xzandro** [comment]
You dont need to download the zip file, because this includes only the raw source code. https://github.com/Xzandro/sw-exporter/releases/latest would be correct.
