### ISSUE TITLE
Cannot pull account logs mac

### ISSUE THREAD

**Issue by tkpritch221** [Xzandro/sw-exporter#32]
Not sure how to pull the account logs. Seems like it should happen upon login but I'm not getting anything. I am able to log friend visits, dungeon runs, and black market just fine. This happening to anyone else? Please advise!

Using version 14 on Mac / iOS

**Comment by Xzandro** [comment]
Hi, did you activate the ProfileExport plugin?

**Comment by tkpritch221** [comment]
Yeah, tried it with/without other options checked.

**Comment by Xzandro** [comment]
Thats weird. You definitely need to activate the ProfileExport, then you need to start Summoners War. btw.: the file is in a folder on your desktop called 'Summoners War Exporter Files' by default. You can change that location in the settings.
