### ISSUE TITLE
[BUG] live file no longer generated when using a grind

### ISSUE THREAD

**Issue by mightormagic** [Xzandro/sw-exporter#320]
**Describe the bug**
The live sync setting is Enabled. Before when I use a grind, swex would generate a live file in the live folder, so that it will sync with swop. Now it seems using a grind will no longer generate a live file. Selling a rune would still generate a live file. I was using nox.

Other aspect of swex works fine.

![image](https://user-images.githubusercontent.com/42580452/82337707-11cf8180-99ba-11ea-91bc-67362ba8b3b2.png)

**Desktop (please complete the following information):**
Windows 10
10.0.18363

**Comment by Xzandro** [comment]
THis is already fixed in the code via commit https://github.com/Xzandro/sw-exporter/commit/352a63871ca4435c4cfe625421b4c2d156fa5eed, but not released yet. Thanks for reporting.
