### ISSUE TITLE
No internet connection possible

### ISSUE THREAD

**Issue by Rhaynn** [Xzandro/sw-exporter#324]
Hello, 
i've been having trouble with connecting my cell to the internet connection with the proxy on. It always says "no internet connection possible". I turn firewall and protection off and still nothing. I tried the https/https switch and nothing. In the past it wroked just fine, but with the 0.0.3 version it stopped working. Now it says I need an API key, which i can't find, but it should only be an issue with exporting file and not the internet connection. I don't know what to do anymore. It has been 6 months now and i can't figure anything out.

**Comment by Xzandro** [comment]
You dont need an API key. This is for the SWAFARM plugin and totally optional. General connectivity issues are usually caused by firewall or security sofotware blocking SWEX. Please set an exception for SWEX.
