### ISSUE TITLE
[BUG] Unable to change the directory for generated files

### ISSUE THREAD

**Issue by Macharius92** [Xzandro/sw-exporter#325]
**Describe the bug**
Unable to change the directory where files are generated

**To Reproduce**
1 In Settings
2 Click on Change in the App/Files Path section
3 Select a new directory and validate

**Expected behavior**
The field should show the new path selected and files should be generated there

**Desktop :**
 - OS: Windows 10
 - Version 0.0.34

**Additional context**
Workaround by changing the value directly in the Config.json is working but not very user friendly.

**Comment by Xzandro** [comment]
Thanks for reporting. This will be fixed in the next release. Not sure when I will release a new version yet tho.
