### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by VIENSHAW** [Xzandro/sw-exporter#326]
Whenever i open swex it will come up, how can i fix it?
SWEX version is [0.0.34]
Windows 10, 64 bit
![微信图片_20200629230504](https://user-images.githubusercontent.com/36757165/86022568-242ee780-ba5d-11ea-8260-bece9a20361d.png)

**Comment by Xzandro** [comment]
This does seem more like a plugin issue. Make sure you dont use any plugins in the plugins folder that dont work or arent actually SWEX external plugins.
