### ISSUE TITLE
[ANDROID] downloaded cert but i cant get passed the "HIVE connection failed" when i try to load the game 

### ISSUE THREAD

**Issue by mdz051** [Xzandro/sw-exporter#329]
title. i have been trying to get my json file using SWEX without having to download an emulator because i do not want to risk getting banned.  it shows that i have the NODEMITproxyCA in my user certificates. please help im not sure where to go next.

**Comment by Xzandro** [comment]
This will only work for Android 6 or lower.

But currently you can do it the old way, since com2us disabled HTTPS. You need to disablew the HTTPS mode option in the SWEX settings first tho to work the old way without a CERT.

**Comment by mdz051** [comment]
Thank you very much! It works perfectly fine now. TYTYTY
