### ISSUE TITLE
[BUG] Summoners War detecting apps that prevent game from opening

### ISSUE THREAD

**Issue by EyeKendy** [Xzandro/sw-exporter#334]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
After I start proxy and try to run the game, Summoners War now prevents me from opening the game as it says its  detects another software that will prevent the game from launching. When I turn proxy off, I can access summoners war with no issue.

**To Reproduce**
1. Go to 'SWEX'
2. Click on 'Start Proxy'
3. Go To 'Summoners War'
4. Click on 'Start Game'
5. Error pops up

**Expected behavior**
Program was able to run 2 days ago. Not sure why this has occurred. Did not see any updates from Com2us as well.

**Screenshots**

**Desktop (please complete the following information):**
Tried on Bluestacks 

**Smartphone (please complete the following information):**
Tried on Huawei Mate 20 Pro, Oneplus 5T and Huawei MediaPad M5 Lite, all on latest android patch.

**Additional context**
For the phones and tablet, seems like as long as I am connected to wifi, it does not allow me to start the game saying that it cannot connect to the game network. Works fine for my desktop on bluestacks.

**Comment by kunsey** [comment]
I've met the same question, looking forward to a solution.

**Comment by EyeKendy** [comment]
Hi Kunsey,

I've found a workaround for Bluestacks but not for mobile. For Bluestacks, you just need to unroot the application and it works fine again.

For mobile, it still does not work on wifi unfortunately. I've contacted Com2Us and they've informed me to first clear my cache and then reinstall the game. Both of which I have not done due to commitment to other things. If you have tried and it worked, please let me know.

regards,

Zachary

**Comment by Xzandro** [comment]
Are you sure that this is SWEX related? Someone had the same issue, that it supposedly didn't work with SWEX. Turned out, that it was not SWEX related, since it didn't work for Wifi in general, even when SWEX wasn't added in. If it's really only with SWEX enabled, quite frankly, I probably wouldn't know a fix, since all SWEX does it proxieing requests and nothing else.
