### ISSUE TITLE
JavaScript exception on first boot (Windows)

### ISSUE THREAD

**Issue by Rexx04** [Xzandro/sw-exporter#339]
I don't know what happened. I've used this same version before with no issues.
The only thing different (I think) is that I've updated my laptop to Windows 20H2.
![2020-10-31](https://user-images.githubusercontent.com/29173349/97792182-6b122280-1ba0-11eb-9215-dce646428db7.png)

**Comment by Xzandro** [comment]
It's because swarfarm is done. THis shouldnt effect the general export functionality tho. https://github.com/PeteAndersen/swarfarm/issues/159

**Comment by Cptkrawall** [comment]
sry i didnt see it :)
