### ISSUE TITLE
Proxy Not Working

### ISSUE THREAD

**Issue by FleecySpring5** [Xzandro/sw-exporter#34]
I've been trying to set up the proxy for summoners war for a few days now, and it has not worked. Every time I have started the process, the proxy started up, my phone connected just fine, but when I try to startup summoners war it gives me an error that says it can't connect to host server or network delayed try again later. Please help me with this asap.

**Comment by Xzandro** [comment]
Usually its because of wrong IP or Port in your phones Wifi settings OR your firewall / antivirus software is blocking the access. Pls disable all antivirus and firewalls (yes, windows has a built in one too).
