### ISSUE TITLE
Nodejs binaries

### ISSUE THREAD

**Issue by CallMeFabioo** [Xzandro/sw-exporter#342]
How did you create the node binaries?

I'm trying to run and I getting this error:
```js
was compiled against a different Node.js version using
NODE_MODULE_VERSION 76. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

I try different versions but get the same error.

Thanks!

**Comment by Xzandro** [comment]
The binaries are pre-compiled to obfuscate the decryption key from the code. So you have to use the specififc electron version stated in the package.json.
