### ISSUE TITLE
Are you going to implement a way to load custom plugins?

### ISSUE THREAD

**Issue by dotbanana** [Xzandro/sw-exporter#35]
See title.  
I wrote some custom-stuff for SW-Proxy mostly for guild-management(i have a script for example which logs automatically if someone of the guild got more than the 6 bonuspoints in guildwar) and i would like to migrate to your tool. I am new to javascript, nodejs and so on. I saw your post on reddit:  
>install node.js (v7.4.0) 
>git clone https://github.com/Xzandro/sw-exporter.git  
>npm install  
>npm run dev  
>npm start   

Are you planning to do it like SWProxy in the future, so that you throw a script into a folder and it just works or will it always be it the way that you need to build it from scratch? If you are planning a custom plugin-system i am going to wait for that otherwise i am going to try it out the other way with a custom build.

**Comment by Xzandro** [comment]
That is planned. There are some complications with lib and module loading still if you load plugins from a different folder. There are internal plugins available though, which work absolutely fine: https://github.com/Xzandro/sw-exporter/tree/master/app/plugins

Best bet is to use this internal plugin folder for now and create a custom build which is really easy with `npm run dist win:64` for example. If you think more people would benefit from it, feel free to create a PR.
