### ISSUE TITLE
Decryption issues on servers located in China

### ISSUE THREAD

**Issue by VIENSHAW** [Xzandro/sw-exporter#353]
SW-Exporter can't catch json after two times separate server maintenance of China server in last week. The SW-Exporter version is 0.0.36 and can work normally by using the simulator before the server maintenance. I try on it on another device and the final result is not working.
Is this a server problem or something goes wrong?

**Comment by mightormagic** [comment]
I got this message for both https mode or normal mode.

![image](https://user-images.githubusercontent.com/42580452/102792025-e65cad00-4375-11eb-8c7a-85722f63ca03.png)

**Comment by playzyx** [comment]
I also encountered this issue today

**Comment by uncompleted** [comment]
It was no problem login via SWexporter proxy, but no data was downloaded. Could you help check? China server.

**Comment by 18612962616** [comment]
It was no problem login via SWexporter proxy, but no data was downloaded. Could you help check? China serve

**Comment by 18612962616** [comment]
It was no problem login via SWexporter proxy, but no data was downloaded. Could you help check? China serve

**Comment by 18612962616** [comment]
It was no problem login via SWexporter proxy, but no data was downloaded. Could you help check? China serve

**Comment by 18612962616** [comment]
sad...

**Comment by 18612962616** [comment]
Error decrypting request data - ignoring. Error: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH

**Comment by 18612962616** [comment]
happy new year！
Is it Ok?

**Comment by Xzandro** [comment]
Please stay on topic. I didn't look into it yet, but if it's really a new key I can't really do anything about it, since I'm not that knowledgable in that regard.

**Comment by sssssssq** [comment]
It may be a problem with http-mitm-proxy .
I use fiddler catch data-package,  smon_decryptor can decrypt .

**Comment by uncompleted** [comment]
I tried use summoners  guru, it worked for China server. It shouldn't be some new keys.

**Comment by Xzandro** [comment]
This commit will fix this issue. I need to release a new version of SWEX now, but there is still a PR pending for SWARFARM. I will ask QuatZo if #355 can be merged or not.
Either way I will release a new version within 24 hours.

**Comment by Xzandro** [comment]
This is released in the [latest release](https://github.com/Xzandro/sw-exporter/releases/latest).

**Comment by alkanna** [comment]
Hey @Xzandro , is it normal to get this error again ? Eu server, when doing raid x30 : "functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH" on event battleRiftOfWorldsRaidCreateSingle
