### ISSUE TITLE
Exporter not logging any longer

### ISSUE THREAD

**Issue by saebi1** [Xzandro/sw-exporter#359]
Hi there,
in the past the exporter (last version v0.0.37) worked fine for me. Since today I have got the problem it's not creating a json file any longer. My iPad can start the game using the proxy (no black screen at the beginning or something else). My iPad has got the last update (iPadOS 14.3) more than two weeks. My computer has not been used since last time I created a json-file few days ago. So no new things installed/uninstalled. --> No chance on my side since last creation of a json-file. 
I restarted both devices and installed the cert-file for a second time on the iPad, but without success. 
Am I the only person who has got that issue currently? Any suggestions how to solve the issue? Many thanks in advance

edit: I started an older version of the exporter (0.31) and I was able to create a json-file. Now I am even more confused

**Comment by kultawanich** [comment]
Same for me as well.

**Comment by LucasSimm** [comment]
exactly the same is happening to me. 0.36 and 0.37 do not generate de JSON file

**Comment by andreaparini** [comment]
I can confirm versions 0.37 and 0.35 do not generate JSON files. I'm using nox on android 5 version. I can log in SW with proxy active, and I have tried several times reinstalling the cert

**Comment by asteriuszzz** [comment]
same heree!! I cant use swop rn without json file please help

**Comment by CHG1731** [comment]
Seems like they changed the endpoint and/or maybe the encryption key as well. Might take a moment to fix this.
The reason it seems to be doing nothing is because it's waiting for a call to /api/gateway_c2.php, but in the newer version of SW this endpoint never gets called.

**Comment by Willmutz** [comment]
Have the same problem. Tried diffrent networks and diffrent ports but the program just say "Listining to the port" And nothing happens :(

**Comment by h20ray** [comment]
they enabled https again..

**Comment by LucasSimm** [comment]
> they enabled https again..

I just enabled HTTPS and it worked! Thanks

**Comment by Willmutz** [comment]
When i try with https i get Failed to connect with the network. Please try again later. (S:9)

**Comment by kultawanich** [comment]
> When i try with https i get Failed to connect with the network. Please try again later. (S:9)

This is the same

**Comment by CHG1731** [comment]
I derped, I tried to get the JSON file on my newest phone, forgot that for android you can only use an android version lower than 7.

**Comment by Zekarlo73** [comment]
I had the same problem but I download certificate and install in my iPad and has create the json file with https option activated

**Comment by Xzandro** [comment]
HTTPS is enabled again. You need to enable HTTPS mode in the SWEX settings also do additional steps.

Everything you need you know is here: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/
