### ISSUE TITLE
[BUG] Proxy events are not getting called upon login

### ISSUE THREAD

**Issue by hugoj-goncalves** [Xzandro/sw-exporter#363]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
My last working export was 17/01/2020
I tried debugging and it seems the proxy events are not getting called anymore for some reason
"HubUserLogin", "GuestLogin", "getUnitStorageList", etc
Is it just me? o.o

**To Reproduce**

1. Start the proxy
2. Restart the summoners wars (kill process and reopen)

**Expected behavior**
Should export data (proxy method I'm guessing)

**Desktop (please complete the following information):**

- Win10

**Smartphone (please complete the following information):**

- Device: Bluestacks 4.250.0.1070 (default config)

**Additional context**
The proxy is actually "working", if I close the exporter summoners wars cant reach its servers

**Comment by hugoj-goncalves** [comment]
Oh, nvm... just found the news at the discord channel.
My bad.

**Comment by sparhawk07** [comment]
I ran into this error as well, as of this moment.  Is there a solution

**Comment by hugoj-goncalves** [comment]
Https must be enabled
