### ISSUE TITLE
[BUG] Not seeing httpsMode checkbox (on macOS Big Sur)

### ISSUE THREAD

**Issue by deirdresm** [Xzandro/sw-exporter#366]
There is no httpsMode checkbox on my version (0.0.37) of SWEX. This foiled my attempts to use https.

**Describe the bug**
The expected checkbox is not there. I've looked at the code, it seems like it *should* be there, so I'm mystified why it wasn't.

**To Reproduce**

1. Be on macOS Big Sur.
2. Download macOS SWEX.
3. Start it and view Settings.
4. Download current SWEX code.
5. Hand-build macOS SWEX.
6. Start it and view Settings.

3 and 6 produced the same result for me: no https checkbox. 

**Expected behavior**

Should be able to check the https checkbox, but can't if it's not there.

**Screenshots**

<img width="801" alt="Screen Shot 2021-01-21 at 18 53 54" src="https://user-images.githubusercontent.com/10251429/105439630-0e138f00-5c1a-11eb-9bef-6c7abbef79b5.png">

**Desktop (please complete the following information):**

- macOS 11.1 (Big Sur)

**Smartphone (please complete the following information):**

- iPad Mini
- OS: 14.3

**Additional context**

Workaround in case you run into this to enable https: 

1. Go into the Settings Path directory, then edit storage/Config.json and set httpsMode to true instead of false.
2. Save the file and close it.
3. Re-launch SWEX.

**Comment by Xzandro** [comment]
I have nothing to offer here. The setting is clearly in the code. https://github.com/Xzandro/sw-exporter/blob/4a4315711b6b411718af29678f620b6caf959941/app/pages/Settings.js#L80

I have to assume, that your local dev environment is not up to date. There were huge changes a few weeks ago, so that wouldn't surprise me. I will leave it open for now in case this really is a general issue for others. I can't see how tho.

**Comment by Xzandro** [comment]
What I noticed from the other issue: you said you tried it with `npm run dist`. THis will NOT rebuild the UI tho. You have to do `npm run pack` or `npm run dev` as described in the [readme](https://github.com/Xzandro/sw-exporter#building-packages).

**Comment by deirdresm** [comment]
Yep, that was it, I forgot that step this time. *facepalm*

As for it seeing the same thing on the distribution, sometimes there's a weird iCloud thing where it'll cache older versions of files seemingly at random (very annoying with frequently updated technical books), so I have now excluded my /Applications directory from iCloud backup. So that may have been a separate cause where it was seeing the old UI.

Sometimes, when I try to upload manually to SWOP, it'll ask which of 6 versions of my profile I want to upload. :P

Thank you, and sorry about that.
