### ISSUE TITLE
[BUG] SWOP Pro - SWEX App/Web No functionnaly

### ISSUE THREAD

**Issue by KrnosTV** [Xzandro/sw-exporter#368]
Hello,
I took a $ 5 Patreon subscription for SWEX Web and bought the pro version of SWOP out of there a few issues:
1. SWOP pro abruptly quits when I run a calculation for my builds
2. SWEX Web is strictly not working (I am using the right port but the connection is not made between your server and me)
3. SWEX App despite having re-checked the "HTTPS" box does not export a Json file (I have read topic # 359 but no solutions exist).

I would like to point out that everything will work perfectly on January 2, 2021

Looking forward to having a real solution or a refund!

------------------------------------------------- (In french for the french community) --------------------------------------------------
Bonjour,
J'ai pris un abonnement Patreon à 5$ pour SWEX Web et j'ai acheté la version pro de SWOP hors il y a quelques soucis :
1. SWOP pro se ferme brutalement quand je lance un calcul pour mes builds
2. SWEX Web ne fonctionne strictement pas (j'utilise bien le bon port mais la connection ne se fait pas entre votre serveur et moi)
3. SWEX App malgré avoir re-cocher la case "HTTPS" n'exporte pas de fichier Json (j'ai bien lu le topic #359 mais aucune solutions existent).

Je tiens à signaler que tout fonctionner parfaitement le 2 Janvier 2021

Au plaisir d'avoir une solution réel ou un remboursement !

**Comment by Xzandro** [comment]
This is only for the SWEX app. Regarding SWOP Pro, you can fix this crash by just updating SWOP to the nwest version. Regarding SWEX Web, it's is not functional. You also need additional steps now for the normal SWEX app as well after the HTTPS change. See #359
