### ISSUE TITLE
Enable "runs.csv" output from swproxy

### ISSUE THREAD

**Issue by DemonSkye** [Xzandro/sw-exporter#37]
One of the key components to an addon I was writing was the runes output, in the current format it's not easily possible to analyze the most recently dropped rune in the logs generated by this plugin.

**Comment by Xzandro** [comment]
Thats is planned and will be available soon. But we will only support the runs.csv. Everything else is either rather useless or its covered in combination with other tools. Like GW logging: https://gw.swop.one/ etc.

See #16

**Comment by DemonSkye** [comment]
Whoops, meant runs, put runes.  Derp.

**Comment by Xzandro** [comment]
Since you are the guy, who tried to create the runeevaluation java tool I highly recommend to look into the JSON file instead to get your data btw. Either the normal JSON or you also could use the live sync action JSON files, which always have all the data needed & in a probably better format to analyze those things.

**Comment by DemonSkye** [comment]
I haven't had time to look at the formatting quite yet, how are the runs nested?  Reading the last line off a csv file is pretty simplistic, finding the last json object is a bit more heavy without introducing dependencies (which doesn't cause much concern to any node based project I suppose, since they all have a zillion dependencies)

**Comment by Xzandro** [comment]
Its file based. So after each run a JSON file will be created with the rune data and meta data like wizard_id, action and a unix timestamp. Just activate the LiveSync plugin and see for yourself. Maybe thats already sufficient.

**Comment by DemonSkye** [comment]
After looking at it, in theory, it's possible.  But that is a LOT of JSON to digest in order to determine if there's a rune and what the stats re on it.  I do appreciate the looking at something better in the future.

**Comment by Xzandro** [comment]
No worries. RunLogger plugin is pretty much done and only needs some testing.

**Comment by Xzandro** [comment]
#41
