### ISSUE TITLE
[BUG] .Json file isn't generated anymore

### ISSUE THREAD

**Issue by Shabadouw** [Xzandro/sw-exporter#379]
Hi, 
I'm having some issues using SW Exporter to get my .json file. 
I'm using Nox emulator for it. Until now, it always worked fine.

When i start the proxy and launch Summoners War, the file isn't created anymore in my Summoners War Exporter Files.
I asked few of my friends who are using it too, and it's the same for everyone : no file generated.

Could it come from a recent SW's update ?

Thank you for your time

**Comment by lucas-enqueiroz** [comment]
Same to me...

**Comment by Xzandro** [comment]
Duplicate of #359
