### ISSUE TITLE
SWEX Web - Failed to connect with the network

### ISSUE THREAD

**Issue by arzelia** [Xzandro/sw-exporter#381]
I'm a patreon and having some problems running the game to get the json file.

- Visited https://swex.swop.one/
- Clicked Unlock on my mobile device (iphone) that I play SW on
- Went into Wifi to set the proxy to proxy.swop.one port 3030 while the 5min unlock timer is still up
- Load SW, getting a "Failed to connect with the network. Please try again later."

Is there anything I missed?

**Comment by Xzandro** [comment]
THis is not about SWEX Web. SWEX Web is not working tho. Closing here.
