### ISSUE TITLE
[BUG] RTA runes do not sync

### ISSUE THREAD

**Issue by maitree78** [Xzandro/sw-exporter#393]
Hi,

I can export my normal runes and monster's sets but it doesn't work when i active the RTA option, then my monsters seems to have some many runes missing. what can i do please ?

maitree78

**Comment by Xzandro** [comment]
I dont see how this is SWEX related? SWEX uses the data provided by com2us and dumps it into a file. SWEX also does not display the monster data. If you mean that this is not displayed in SWOP, it's a completely different thing.

Please give more details, if it is not related to SWEX I will close this.
