### ISSUE TITLE
Unexpected error when logging Artifact Dungeon Runs

### ISSUE THREAD

**Issue by Staxed** [Xzandro/sw-exporter#398]
**Describe the bug**
When running Artifact Dungeons with active run logging enabled, there is an unexpected error occurring.  It does not happen all the time, so I am assuming the program is simply missing some of the new attributes that were added after the Artifacts were updated a few months ago.

An unexpected error occured: this.artifact.effectTypes.sub[type] is not a function

**To Reproduce**
Have run logging enabled, run either Artifact Dungeon.

**Expected behavior**
"Saved run data to xxx.csv".  This does happen occasionally, but most of the time it is the error listed.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 20H2

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro
- OS: iOS 14.6

**Comment by Xzandro** [comment]
Technically this should already fixed in master via https://github.com/Xzandro/sw-exporter/commit/a4fc89b00c6b7f6ace02c29915b10cfe40e8fc38

It's just not released yet.

**Comment by Xzandro** [comment]
Released in 0.0.40
