### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by wanderingkittenn** [Xzandro/sw-exporter#399]
idk im using windows and im trying to use this on ios but it doesnt do anything

**Comment by Xzandro** [comment]
This repo is for issues within the code. I can guarantee you, that it does work, especially for iOS if you follow the additional cert steps.

**Comment by wanderingkittenn** [comment]
> This repo is for issues within the code. I can guarantee you, that it does work, especially for iOS if you follow the additional cert steps.

_well maybe if you included some itll work_

**Comment by Xzandro** [comment]
This issue #359 is literally pinned.

**Comment by wanderingkittenn** [comment]
> This issue #359 is literally pinned.

i got the cert on my phone and it doesnt connect and ive done everything

**Comment by wanderingkittenn** [comment]
![E2F550EC-3656-4D00-92B1-BB64A5127B06](https://user-images.githubusercontent.com/88068479/127417985-6c0f8cad-0eda-4ca5-bdbd-a5900b8140c3.jpeg)
![0F4823C6-CB85-455B-8F68-ADD59AB22C20](https://user-images.githubusercontent.com/88068479/127417994-2ae32e6c-ea27-42b4-bece-88796969a028.jpeg)
yes ive pressed start proxy on pc and did everything else
