### ISSUE TITLE
[BUG] Linux 0.0.43 AppImage only binds to localhost interface and not all interfaces

### ISSUE THREAD

**Issue by stryhf** [Xzandro/sw-exporter#415]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
Latest iteration 0.0.43 of Linux AppImage appears to only bind localhost (127.0.0.1) instead of universally (0.0.0.0).

**To Reproduce**

1. download and make executable latest Linux AppImage version 0.0.43
2. specify port
3. start proxy
4. check netstat -tl | grep <port>
`tcp        0      0 localhost:7070          0.0.0.0:*               LISTEN`
5. ran strace against program
```
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 82
setsockopt(82, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(82, {sa_family=AF_INET, sin_port=htons(7070), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
listen(82, 511)                         = 0
```
6. the running application specifies the proper IP address and doesn't mention it is binding only to localhost
![image](https://user-images.githubusercontent.com/9879659/132732756-e5a33cc6-b31f-4b25-b172-7f222a5f5115.png)

**Expected behavior**
Previous behavior and current Windows version universally binds to all interfaces (0.0.0.0).

I delved through ~/.config/Summoners War Exporter and the extracted /tmp/.mount_SWEX* directories to see if there was something obvious to specify interface binding but couldn't find anything.

**Desktop (please complete the following information):**

- OS: Linux
- Version:  Ubuntu 20.04.3 LTS

**Comment by Xzandro** [comment]
I dont see how this could happen, since there were no changes to the proxy code or library in that regard. So I dont know how I coulkd change this, nor do I use Linux to play and test around.

Maybe someone else can look into it? Although someone else would consider working on this project sadly. Or you can try to build SWEX yourself on linux?

**Comment by stryhf** [comment]
I walked back the versions and it looks like it was introduced in the pre-release 0.0.41 update.  Unlike for Windows where 0.0.43 fixes the issues, the Linux AppImage is still improperly binding.  I'll see if I can dig through the changes, maybe the network dependencies for Windows didn't apply for the Linux build?

**Comment by Xzandro** [comment]
The only thing I can imagine is, that travis CI cached the node_module. So to apply the new 1 year cert validity I had to fork the proxy library I use: https://github.com/Xzandro/node-http-mitm-proxy 
In there I just updated from upstream first, but that introduced connection issues. So I force pushed it back to version 0.9.0 (the usual version I used for all previous versions) and just applied the simple cert creation validity change.

From there I set it as the [new dependency](https://github.com/Xzandro/sw-exporter/blob/stable/package.json#L88) and I rebuild all the version via travis CI or appveyor:

Logs of builds for [MacOS](https://app.travis-ci.com/github/Xzandro/sw-exporter/jobs/536340258), [Linux ](https://app.travis-ci.com/github/Xzandro/sw-exporter/jobs/536340259) and [Windows](https://ci.appveyor.com/project/Xzandro/sw-exporter/builds/40699141)

All in all, pretty basic stuff I would say.

**Comment by stryhf** [comment]
So digging through the parent node-http-mitm-proxy, I found this.

https://github.com/joeferner/node-http-mitm-proxy/commit/4119422390b77867a00a812eed2a8a088c1f410b

**Comment by Xzandro** [comment]
This is not included in my fork. BUT this kinda confirms my cache suspicion. I MIGHT update to the newest upstream tho and just pass `''` as the host option.

**Comment by Xzandro** [comment]
Until then, you should be able to just build SWEX yourself. Its described in the readme.

**Comment by Xzandro** [comment]
This needs to be tested now. I fully changed the upstream so it is on par with their master. I also pass `''` as the host option.

Since I currently need Hyper-V enabled for Docker I can't use emulators so I will try to let one of my testers test this.

**Comment by Xzandro** [comment]
Sorry for the multiple messages. A tester tested it on Windows and it worked there. I built and released a new version (0.0.44). Feel free to try this out and see if that works now.

**Comment by stryhf** [comment]
I can confirm it works with 0.0.44.

I did have to re-generate the SSL certificate.  The one that was generated with 0.0.41 - 0.0.43 was having issues still.

**Comment by Xzandro** [comment]
Alright. This is closed then. Thanks for reporting.
