### ISSUE TITLE
if i open without https the game works but do not charge the json, with https the game doenst load at all, pls help[BUG]

### ISSUE THREAD

**Issue by davidhsanz** [Xzandro/sw-exporter#423]
first of all thanks for the amazing program
greetings

**Comment by Xzandro** [comment]
This is normal behaviour. HTTPS mode is mandatory, since com2us is using it for a while now. Check out the pinned issue for guides and guidance or [join the Discord](https://discord.gg/JMBSZRA).

**Comment by davidhsanz** [comment]
thx bro, i will


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
