### ISSUE TITLE
[BUG]after i put my laptop ip on phone proxy, the game can't connect to the with web. any other apps works normally. android.

### ISSUE THREAD

**Issue by mrmeny** [Xzandro/sw-exporter#426]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Xzandro** [comment]
SWEX Web is not functional. Also this repository is only for the normal SWEX app.
