### ISSUE TITLE
Javascript error, uncaught exception v0.0.14

### ISSUE THREAD

**Issue by rmattson** [Xzandro/sw-exporter#43]
This error is occuring in the Windows 64-bit portable exe.

> [Main Instruction]
> A JavaScript error occurred in the main process
> 
> [Content]
> Uncaught Exception:
> TypeError: "port" option should be a number or string: null
>     at lookupAndConnect (net.js:961:13)
>     at Socket.connect (net.js:939:5)
>     at Object.exports.connect.exports.createConnection (net.js:74:35)
>     at Server.<anonymous> (C:\Users\rmatt\AppData\Local\Temp\nsuE5E1.tmp\app\resources\app.asar\app\proxy\SWProxy.js:108:27)
>     at emitThree (events.js:116:13)
>     at Server.emit (events.js:194:7)
>     at onParserExecuteCommon (_http_server.js:459:14)
>     at onParserExecute (_http_server.js:418:3)

**Comment by Xzandro** [comment]
Well, what did you set as a port?

**Comment by rmattson** [comment]
Heh, sorry -- port 8080, just the default one when it opens.

**Comment by Xzandro** [comment]
So you didnt change the port at all? Never? That's strange. By default the port is 8080 and the error message wouldnt make sense at all then.

**Comment by rmattson** [comment]
I definitely did not change the port.

The proxy generally works fine. I'll do several dungeon runs in a row with no problem. But every once in a while this error happens, and I notice it now because it ends up blocking the connection from the app. But when I dismiss the error, everything works fine again.

**Comment by Xzandro** [comment]
Can you post me the content of your config file please? Its in the folder `%appdata%\Summoners War Exporter\storage\config.json`

**Comment by rmattson** [comment]
Strangely, there was no config file there.

I went to the settings to see if there was a way to force save the config, and selected the option to 'Start proxy automatically,' and then a Config.json appeared. Here is the contents:

> {"App":{"filesPath":"C:\\Users\\rmatt\\Desktop\\Summoners War Exporter Files","debug":false},"Proxy":{"port":8080,"autoStart":true},"Plugins":{"ExamplePlugin":{"enabled":false},"FriendExport":{"enabled":true,"sortData":true},"FullLogger":{"enabled":false},"LiveSync":{"enabled":false},"ProfileExport":{"enabled":true,"sortData":true},"SwagLogger":{"enabled":true},"SwarfarmLogger":{"enabled":true}}}

**Comment by Xzandro** [comment]
I googled a little bit. That seems to be a strange, general node.js issue, which is basically unsolved. Seems to happen with other apps / frameworks too: https://github.com/meteor/meteor/issues/7615 Nothing we can do about it really, code is fine for that and I cant reproduce this issue.

**Comment by rmattson** [comment]
Cool, thanks for checking on it!
