### ISSUE TITLE
[BUG]SWEX not collecting data on HTTP or HTTPS

### ISSUE THREAD

**Issue by Symsyr** [Xzandro/sw-exporter#438]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
Honestly not sure if this is a bug or just something that hasn't been implemented yet.  Using Windows Subsystem for Android on Win11, I can install and start SWEX, it pulls up my IP address just fine and when I start the proxy, I can connect to SW but it doesn't actually export the data.  I have tried using both HTTPS and regular HTTP but it still doesn't export the data.

**To Reproduce**

1.) Install SWEX on Win11 (I am using Win11 on ARM)
2.) Start Proxy
3.) Launch Summoner's War

**Expected behavior**
SWEX should export my JSON

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win11 on Arm
- Version: Latest version

**Smartphone (please complete the following information):**

- Device: Samsung GalaxyBook S
- OS: Win11

**Additional context**

**Comment by Xzandro** [comment]
Probably because you use Android 7 or higher. Please refer to the very extensive help section of SWEX. At least inthe case for your Samsung GalaxyBook S. Regarding the Android subsystem, didnt use it and probably wont work out of the box, if ever. But you should open a dedicated issue for that if needed.
