### ISSUE TITLE
Error while synchronizing profile with SWARFARM.

### ISSUE THREAD

**Issue by NielasAran0** [Xzandro/sw-exporter#439]
Swarfarm logger doesn't work with my API key, SWEX displays the error in the title when trying to send data.

**Comment by Xzandro** [comment]
This happens if you never uploaded the data file to swarfarm. You could also just enter your API token for swarfarm in the SWEX settings. If you have additional questions, feel free to contact the swarfarm devs directly, since this hasnt much to do with SWEX itself.
