### ISSUE TITLE
[HELP] Proxy certificate older than 12 months

### ISSUE THREAD

**Issue by MiniEve** [Xzandro/sw-exporter#441]
Hi Xzandro,

I tried to use SW Exporter for the 1st time but when I clicked on the "Start Proxy" button, it showed the message : 
**Your certificate is older than 12 months. If you experience connection issues, please regenerate a new one via the Settings**

But I can't find how to renegerate a new one on the Settings menu.

Thank you in advance.

**Comment by Xzandro** [comment]
Here you go: 
![image](https://user-images.githubusercontent.com/3385521/173174745-3796d6ab-fcd8-4845-8c21-1607a937e292.png)
