### ISSUE TITLE
[BUG] Android MuMuPlayer ERR_PROXY_CONNECTION_FAILED, unable to connect to game servers while using SWEX

### ISSUE THREAD

**Issue by Rycia** [Xzandro/sw-exporter#444]
I am having an issue with SWEX.

Previously, I have ran into this issue a few months ago. I was reinstalled my cert for literally about 3-4 hours straight messing with it until I randomly got it to work.

However, I had to reset my PC a week or two ago, and found I had to reinstall SWEX and MuMuPlayer, an android emulator popularly used with SWEX.

**When I did this, I came across the same issue again and have been unable to fix it this time.**

Here's the result.
The screen goes black when in Summoners War's launch for about a minute after the Com2us logo.
![image](https://user-images.githubusercontent.com/43384589/179372423-c6cad648-6d7a-41fb-9cc1-11d05f0e8531.png)
Then the game goes into "Checking for updates,"
![image](https://user-images.githubusercontent.com/43384589/179372525-7ecef6c8-9e32-47f0-86f8-fb94bdd8291d.png)
..and then I get an error from MuMuPlayer following the "Tap to start" again. If I press "Tap to start," the process starts over again with "Checking for updates" following the same error.
![image](https://user-images.githubusercontent.com/43384589/179372551-e8ade03b-59e6-4a3b-af56-560a75273d5e.png)
![image](https://user-images.githubusercontent.com/43384589/179372559-0e9e012c-7f67-40fe-8509-a3deb4e07f7a.png)

Here is the main screen of my SWEX.
![image](https://user-images.githubusercontent.com/43384589/179372625-bbdd61be-2f6e-4193-9a90-cf63f84fa35f.png)
And subsequently, my SWEX settings.
![image](https://user-images.githubusercontent.com/43384589/179372642-33809dca-bd96-4645-b520-de0066a2ec89.png)

I have attempted this with both regenerated certs in HTTPS mode and HTTP mode. _(Not sure if I have to regenerate certs every time I change that, but I did anyways.)_

Additionally, I am reporting this because I am not the only person having this issue and it looks like a lot of the "Issues" are dead links from a long time ago.
Just take a look at the newest comments posted on this video, which I was following to make SWEX work;
[https://www.youtube.com/watch?v=dO43nwmjE9E](url)
I'll screenshot some of those.
![image](https://user-images.githubusercontent.com/43384589/179372702-e449f6cf-9684-4f40-9b2d-d12b45865e35.png)
![image](https://user-images.githubusercontent.com/43384589/179372731-b9062de3-5afa-4a0f-812c-f26e74ac1739.png)
![image](https://user-images.githubusercontent.com/43384589/179372762-2702cb27-44d6-4a79-86d9-53b7fafa6943.png)

If this is a matter of HTTP and HTTPS messing up, I would reccomend someone remove whichever option straight up won't work.
It is a very bad design choice to provide an option within a program designed for a specific app that does not function, and it is room to cause me among others headache. I suggest the option is removed and whichever option SW requires is default without an option to change it.

Until this is clarified and solved, me among others will not bother with SWEX.

**Comment by Rycia** [comment]
Update. I had NordVPN on, and even though I whitelisted SWEX and my emulator, traffic was still somewhere routing through my VPN. _Duhhh._

**Comment by Xzandro** [comment]
Yea, SWEX wont correctly with VPNs involved. Glad you figured it out.
