### ISSUE TITLE
Rune efficiency plugin improvements

### ISSUE THREAD

**Issue by porksmash** [Xzandro/sw-exporter#45]
1. Report world boss runes
2. Report all runes on shop refresh
3. Include star grade in log entry

**Comment by RaspFR** [comment]
Hi Porksmash, 
Just my two cents about how to display rune info on log entry : 

1 - Rune icon displayed according to the rune slot and rune set.
2 - Star grade to quickly know if it's a 6 star or not.
3 - Label color according to the rune quality (already the case).

Thanks a lot to both of you for the great job you've done so far. Keep up the great work ! :)

![runedropplugin](https://cloud.githubusercontent.com/assets/10197265/25199303/b01caa58-254a-11e7-88c6-d2ba752bcd76.png)

**Comment by Xzandro** [comment]
That looks awesome.

**Comment by porksmash** [comment]
I like how that looks! I initially decided against rotating the rune icon around because you end up with either complicated CSS and DOM elements, or a ton of images. This is mostly because of the fact that the rune icon doesn't rotate with the background. I already did the complicated CSS and DOM elements for swarfarm so I'll see if I can leverage that.

**Comment by RaspFR** [comment]
I got your point about css and the icon rotation. So here here my last two cents. 
We can just display the slot info as a text (on the left side of the rune icon in my example) and may be also precise for slot 2,4,6 what is the main stat.
Once again, this is just free ideas. Feel free to take inspiration or not ;)

![runedropplugin2](https://cloud.githubusercontent.com/assets/10197265/25202740/b2e2d09e-2556-11e7-8b72-ded93814d3e4.png)

**Comment by joaokamun** [comment]
Added shop runes efficiency on #79 - Ill try work on other improvements listed by OP.

**Comment by Xzandro** [comment]
I think we have most of the things implemented.
