### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JetDePierre** [Xzandro/sw-exporter#457]
This might be a dumb question, but how do you fix the error on SWEX that keep noticing me "Looking for the following commands to log:" and then a bunch of things like DoRandomWishItem but like at least 50 times
i can't get my json and it's a bit problematic 

otherwise thanks for the amazing work you've done

**Comment by Xzandro** [comment]
Sounds like the SWARFARM plugin and DoRandomWish sound slike you have the ExamplePlugin enabled. Nothing has to do with the general fucntionality of SWEX. Closing also because of extremely low effort bug report without any meaningful additional information.
