### ISSUE TITLE
Crafting runes causes an error message to pop up

### ISSUE THREAD

**Issue by ziprain** [Xzandro/sw-exporter#48]
Everytime you craft a rune ingame there is a short delay and almost instantly an error message pops up on SW Exporter saying: 
![image](https://cloud.githubusercontent.com/assets/25232583/25287047/278d457c-26c0-11e7-9314-6a620b8afbbb.png)
Only tested it on fatal runes "high runes".

Sw Exporter throws the error but after clicking ok it still works and is still connected. The log says:
![image](https://cloud.githubusercontent.com/assets/25232583/25287114/75207c0a-26c0-11e7-9f0f-5e80dcc80673.png)

**Comment by Xzandro** [comment]
Make sure, that you always use the newest version.
