### ISSUE TITLE
"No file selected" on Summoners War Optimizer

### ISSUE THREAD

**Issue by Rhaynn** [Xzandro/sw-exporter#486]
Hello, 

i extracted the JSON-FIle as usual, everything worked fine, but when i want to import it, Opitimizer says "No File selected". Is something wrong with the file or did something change in the last couple of weeks? I didn't have thin issue before. 
Thanks in advance.

**Comment by Xzandro** [comment]
This is about SWEX. SWOP will crash until all the new sets and artifacts substat types etc. were implemented.
