### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by Jongha12** [Xzandro/sw-exporter#489]
Hi all,
I extracted the json file today and imported it into SWOP Pro, but I get a critical error. (Line: 2008)
I'm using Windows 10 and the SWOP Pro version is 3.7.
There is no problem importing the json file that I exported 2 weeks ago.
My json file size is 5.41MB.
My exporter setting is below.
![2](https://github.com/Xzandro/sw-exporter/assets/139413897/183e04aa-575a-4467-912f-ea756ce9baf7)
![1](https://github.com/Xzandro/sw-exporter/assets/139413897/6f86c370-afe6-4be9-9df6-ea94ce09b1ce)
Can you help this issue?

**Comment by Xzandro** [comment]
This is not a repository for SWOP. Please join my Discord or contact me any other way, thank you.
