### ISSUE TITLE
[MuMu] SWEX doesn't generate any informations

### ISSUE THREAD

**Issue by chaot2000** [Xzandro/sw-exporter#497]
I updated SWEX from 0.0.53 to 0.0.55 and from there on it is not possible to get runes, black market or profile file from the exporter.
I reinstalled SWEX and MuMu with the latest versions today. Deleted folder before installation.
Tried with certs and without certs.

No effect. 

Used components:
 SWEX 0.0.55
MuMu-Player 2.7.23 (x64)

Got anyone another idea?

**Comment by xenofree** [comment]
I don't know if it's the same kind of issue but SWEX doesn't generate anything either.

I have this log
```
Error decrypting request data - ignoring. Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
```

I try with a new cert, but without success

**Comment by chaot2000** [comment]
@xenofree  Thanks for that hint.

it is the same issue. here my log:
`Error decrypting request data - ignoring. Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT`

it is independent of the certificates used

**Comment by EstebanRestoy** [comment]
same error here with mumu & sw exporte v0.0.55 :
![image](https://github.com/Xzandro/sw-exporter/assets/55629825/c6a05da2-89b4-42ad-a58a-96058ed1066d)

**Comment by Xzandro** [comment]
https://www.reddit.com/r/summonerswar/comments/16idmio/state_of_swex_after_patch_809/
