### ISSUE TITLE
Http Proxy appears to conflict with latest Mumuplayer 12, possibly not passing through emulator calls

### ISSUE THREAD

**Issue by stryhf** [Xzandro/sw-exporter#501]
Upgraded to the latest MuMu Player 12 (formerly MuMu Player X) https://www.mumuplayer.com/update/

When the HTTP proxy is enabled it appears to eat certain HTTP calls that can affect how the emulator works.

First obvious effect is the homescreen no longer displays the banner ads.  Not a gamebreaker, but it shows a symptom of the issue.

The second issue is when the game starts there is no longer a tab displayed across top that enables app switching.

The third issue is the interface you use to customize the keyboard is no longer available.

Once the HTTP proxy is disabled and instance is restarted all the 3 listed above issues disappear.

Since MuMu is by NetEase and looking at the proxy code it captures "qpyou.cn", is it possibly capturing calls required by the emulator?

**Comment by Xzandro** [comment]
Hi, without looking into it too much, I'm not quite sure what I can do about this. SWEX is pretty basic. It listens in specific requests and just forwards it without any change. But maybe someone else can look into this in depth. I'm usually a bit short on time.

**Comment by Xzandro** [comment]
Mumu 12 should work, you can use this guide for now: https://github.com/EytanMorg/sw-exporter/wiki/3.-Setup-guides#mumu-app-player-12-setup
