### ISSUE TITLE
Dungeon Run Log doesn't label newest dungeons by name (Abyssal Normal & Abyssal Hard) instead labels them as "Unknown" in the dungeon name category. [BUG]

### ISSUE THREAD

**Issue by DaltonCrawley** [Xzandro/sw-exporter#503]
**Describe the bug**
Dungeon Run Log doesn't label newest dungeons by name (Abyssal Normal & Abyssal Hard) instead labels them as "Unknown" in the dungeon name category.

**To Reproduce**

Start a Dungeon Run of Abyssal Giant (Either Normal or Hard)
Complete the Dungeon Run
Go to the runs.csv file on your machine
View the lastest entry to the csv file
Newest Entry should have the date of the run and should immidiately after have the label "Unknown" for dungeon name

**Screenshots**
![Screenshot 2023-11-18 100252](https://github.com/Xzandro/sw-exporter/assets/144277338/0ffee124-6ae3-4f38-bac9-8cdcd4633792)

**Desktop (please complete the following information):**

- OS: MUMU 
- 6

**Additional context**
Don't think this is a difficult fix I just think that the new labels haven't been added since the major update a while back.

**Comment by Xzandro** [comment]
This is already fixed in code with via #500 just not released yet. But until then feel free to build from source.
