### ISSUE TITLE
SWEX exporting the same file over and over again

### ISSUE THREAD

**Issue by Sevisseus** [Xzandro/sw-exporter#504]
**Describe the bug**
Swex giving me the same file and the same file name no matter what cert or proxy port, It's always the same json every time I log into my account even with small changes, same file name and same size alongside with the same info. Even swop.tool tells me that it's the same file when I'm trying to export.

**To Reproduce**
Log into my sw account with proxy on, like how you get your json.

No error, does the same thing it should but there is no new and updated version of my json, even swop.tool tells me that it's the same json when importing.

**Expected behavior**
Simple, a new json file to upload into swarfar and swop.tool

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 10.0.19045 Build 19045

MuMu 12 as the emulator, default settings and the latest version.
It used to work flawlessly though.

**Comment by Xzandro** [comment]
SWEX will never just export the same file. because it does not know the previous file, since it will always get a fresh one from the server directly. Which leads me to believe, that SWEX actually does not export anything in your case. Feel free to check the Log if SWEX exports anything on SW startup. If not, make sure to follow troubleshooting steps from the Help section and make sure you setup everything correctly.

**Comment by Sevisseus** [comment]
It openly says that it has exported the said json, "Saved profile data to LD-V5I-35721103.json" With a green checkmark indicating that it just had exported it but that's not really the case.

It's always the same file name with the same data, Regenerating the cert and changing to port from 8082 to 8081 (After changing the innital cert's port as well of course.) It's pretty much the same without any change.

I' not sure in any of the cases but it just seems like it's exporting the same file over and over again because the json's time of modification (Date and time) Always refreshes every time it exports? It's the same file without the new data.

Is it also because I'm using Mumu12 instead of the other safer alternatives that are android 5 and below? I mean, SWEX stopped exporting correctly one day and that's much about it.

**Comment by Xzandro** [comment]
Another possibility is that SWEX does not have access to the existing file. This can often happen if it is in a folder, that gets backed up by some kind of Cloud service, like OneDrive or Dropbox. Again: there is no way, that SWEX would export an identical file. But it can happen, that SWEX does not have sufficient permissions to overwrite the existing file. You could try to start SWEX as Admin or change the file path in the SWEX settings.
