### ISSUE TITLE
Version for Steam application?

### ISSUE THREAD

**Issue by edward-sciberras** [Xzandro/sw-exporter#508]
Was just wondering if there will be a version that can be used for the Steam version of the game that was released recently.

**Comment by Xzandro** [comment]
https://www.reddit.com/r/summonerswar/comments/195sg7h/experimental_way_to_use_swex_with_steam_version/

Would also recommend getting information via [my Discord server](https://discord.gg/JMBSZRA).

**Comment by edward-sciberras** [comment]
Thank you for the help :)
