### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tianvay** [Xzandro/sw-exporter#512]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
When running steam mode, and launching SW on steam, SW gets no connection. As soon as I turn the proxy off, the connection works again. I have not enabled a VPN and Windows Firewall ist off. Are there any log files I could upload to help?
I do have a FritzBox, do I need to open any ports?

**To Reproduce**

1. Go to Start Proxy
2. Click on Steam Mode
3. Start SW on Steam
4. No connection in SW
5. Turn off Proxy
6. SW on Steam works again.

**Expected behavior**
SW should connect to Com2Us Servers.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10

**Comment by Xzandro** [comment]
If it's the S:10 error, that is a strong indicator that something wrong is with your cert. Either expired or not installed correctly. Since you did not say that you installed the cert to the trusted windows cert storage, you just forgot to do so. Full steps are in the help section.

**Comment by tianvay** [comment]
That is partially correct, I did not install the cert. However, even after following the instructions at [https://asu.my.salesforce-sites.com/kb/articles/FAQ/How-Do-I-Add-Certificates-to-the-Trusted-Root-Certification-Authorities-Store-for-a-Local-Computer](url),
I still get the S10 error. The generated ca.pem also shows that it is last edited at 20.09.2020, despite being freshly generated.
Of course SWEX then complains again that the cert is older than 12 months...
I am using the portable version, should I try to install the other one?
Also it is possible that there is an old version on my PC, would that interfer?
Is it possible to generate logfiles or something so it would be easier to troubleshoot?

I know "it doesn't work" is a bad report :(

**Comment by Xzandro** [comment]
Regenerate the cert via Settings -> Regenerate cert. Only then a fresh cert will be generated.

**Comment by tianvay** [comment]
That absolutely worked. Thank you so much.
