### ISSUE TITLE
[BUG] Getting error that the hosts file is in use by another process and I've confirmed multiple ways there is no process using the hosts file.

### ISSUE THREAD

**Issue by Dmoua68** [Xzandro/sw-exporter#517]
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
Getting error that the hosts file is in use by another process and I've confirmed multiple ways there is no process using the hosts file.

**To Reproduce**
Steps to reproduce the behavior: Click Start proxy > Steam Mode

**Expected behavior**
Application should be able to access the hosts file and run the proxy

**Screenshots**
![image](https://github.com/Xzandro/sw-exporter/assets/120354975/426c06ff-39ff-4d95-bb89-835a07aa9353)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.0.62

**Smartphone (please complete the following information):**

**Additional context**
I've confirmed via process explorer app and the resource monitor tool that the hosts file is not in use when launching the proxy in steam mode. Found online that it could be AV that could be locking the file. I've disabled protection from my AV and tested with the same issue.

I am launching the tool as an admin.

![image](https://github.com/Xzandro/sw-exporter/assets/120354975/1ffb9326-3e4a-4db4-b555-42ce151055f5)
![image](https://github.com/Xzandro/sw-exporter/assets/120354975/da535cb8-ed43-45ba-be0b-49f189d2152f)

**Comment by Xzandro** [comment]
Probably not a bug. In the past this was caused by some kind of security software.
