### ISSUE TITLE
ProfileExport not exporting anything

### ISSUE THREAD

**Issue by bubbagump91** [Xzandro/sw-exporter#52]
Not getting an exported profile.  I am getting activity in the full_log.txt, and ProfileExport is enabled.

I don't get any error pop-ups and am not seeing any errors in the full_log either.

Is there anything else I can do to troubleshoot ?

**Comment by Xzandro** [comment]
Did you look in the right folder? Desktop -> Summoners War Exporter Files is the default one.

**Comment by bubbagump91** [comment]
Same place as the full_log.txt and [me]-[wizard_id]-runs.csv files, right?  No .json files in there.

**Comment by Xzandro** [comment]
Can you post screenshots of your settings and Log? Never heard of such an issue.

**Comment by bubbagump91** [comment]
![swe](https://cloud.githubusercontent.com/assets/10873720/26280380/00f07de4-3d9f-11e7-920e-f3ef80658138.png)
[full_log.zip](https://github.com/Xzandro/sw-exporter/files/1016589/full_log.zip)

(wizard_id and account name changed- if you need those I can provide over email)

**Comment by Xzandro** [comment]
That other issue is already fixed, so that is 100% not the problem. You know, that this file is only created on Summoners War start yea? Try to restart Summoners War and see if the file is generated.

**Comment by bubbagump91** [comment]
Yea.  I have even closed out of SW and restarted my phone while the proxy was running.  Still no file after signing in to SW again.

**Comment by bubbagump91** [comment]
OK, after a lot of messing with things I eventually figured it out.

The account was never associated with any accounts (Facebook, Hive, etc) so it was just stored locally.  Kind of makes sense that it couldn't be scraped from the network traffic if it's only stored locally..

Not sure they even let you do that anymore, so might not be that big a deal going forward.
