### ISSUE TITLE
Proxy Error OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH

### ISSUE THREAD

**Issue by rahmadiyann** [Xzandro/sw-exporter#521]
The error shows up pretty much everytime I did basically everything, opening the game, opening black market, etc. It doesn't seem to affect anything other that I realize my data doesn't get sent up to SWARFARM (which i think it doesn't have anything to do).

**To Reproduce**
1. Pretty much everything I did in game produces the Error

**Screenshots**
<img width="614" alt="image" src="https://github.com/Xzandro/sw-exporter/assets/81454957/bb4e135b-2ba0-491c-8637-e6df0ee4a6cb">

**Desktop:

- OS: MacOS M1
- Sonoma 14.4.1

**Comment by Xzandro** [comment]
This is just an indicator that some commands use their new decryption process. This is in fact not an error, it is a debug message. Feel free to disable debug messages, since its only for devs or when you have other issues as troubleshooting steps.
