### ISSUE TITLE
[BUG] can't use the app 

### ISSUE THREAD

**Issue by Kinphan** [Xzandro/sw-exporter#522]
Hi i got a error msg whenever i start the proxy and i don't know how to fix it i already tried to reset the certificate
![swbug](https://github.com/Xzandro/sw-exporter/assets/87127482/bf0fc277-662b-44f9-b1a3-9fa379ae7fca)

**Comment by Xzandro** [comment]
Something is listening on this port 443 already on your PC, like a service or other program. Not a bug of SWEX.

**Comment by Kinphan** [comment]
Ok thanks you ive left apache open without you i would never figured it out
