### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Blokade1** [Xzandro/sw-exporter#525]
**Describe the bug**
</>Proxy
Error decrypting request data - ignoring. Error: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH

**To Reproduce**
I unlock from SWEX Web, start proxy, start summoners war in steam mode then open it up from steam.
once logged in the above bug reoccurs every 30 seconds

**Expected behavior**

**Screenshots**
![Screenshot for summoners war error](https://github.com/user-attachments/assets/87e04b1f-f740-4407-b53c-25821030aff7)

**Desktop (please complete the following information):**

- OS: Windows
- Version, Latest Feb 18

**Comment by Xzandro** [comment]
This is no bug. These are debug messages you enabled, which are only relevant for devs.
