### ISSUE TITLE
[BUG] Unable to trust certificate

### ISSUE THREAD

**Issue by uncompleted** [Xzandro/sw-exporter#528]
When install the cert from SWEX, NodeMITMProxyCA, the next step should go to setting, about to toggle on the Certificate trust, but there's no option there.
**Screenshots**
![786045801](https://github.com/user-attachments/assets/8d752672-5ba1-47ac-8f67-e9c8b9ef911d)
![96242693](https://github.com/user-attachments/assets/c8be4530-1c4a-4604-a602-d395bc3141a2)

iPhone 12 Pro Max, iPhone 15
- OS: iOS 18.0.1
- Version

**Comment by Xzandro** [comment]
Not a bug with SWEX.
