### ISSUE TITLE
Elemental Rift Dungeons not logging

### ISSUE THREAD

**Issue by desert-jay** [Xzandro/sw-exporter#53]
I have switched from the SWProxy and I am not sure if I have something set wrong. It is logging all of my dungeon runs except for the Rift Dungeons. I am attaching a screenshot to show what I have checked in settings. 

Do I need to change something?

![settings](https://cloud.githubusercontent.com/assets/4443498/26322462/0d578d7e-3ee0-11e7-8707-bf7642034f4c.PNG)

**Comment by Xzandro** [comment]
Local Rift logging is currently not supported.

**Comment by Xzandro** [comment]
As of 0.0.18, that is now possible.
