### ISSUE TITLE
[Error] Proxy: Could not modify hosts file: Enountered an error: User did not grant permission.

### ISSUE THREAD

**Issue by Havetotrain** [Xzandro/sw-exporter#533]
I need help.

Used to run SWEX on Steam-Mode already. Since the last Update im getting that error mentioned above as soon as im starting the proxy. 

I already reinstalled / regenerated the cert and im using SWEX on admin mode. Also tried to enable like every function of SWEX step by step. So far nothing worked for me.

Any ideas?

Thank you :)

**Comment by Xzandro** [comment]
Most likely not SWEX code related and an issue with security software.
