### ISSUE TITLE
Java script error occured in the main proccess

### ISSUE THREAD

**Issue by xINTELL** [Xzandro/sw-exporter#55]
After 3 days of not using the exporter, I turn it on and do everything in order and get this message

http://prntscr.com/fc7wdk

**Comment by Xzandro** [comment]
Weird error. Did you open the file with another program maybe?

**Comment by porksmash** [comment]
If it's a permissions error, it's either open (and locked) from somewhere else or SWEX doesn't have permissions to write to that file. Try changing the folder, checking that the file is not read-only, etc.

**Comment by xINTELL** [comment]
No it's not read only. I did use it to export my runes from SW once but that was it if you count that as opening it. other than that no.

**Comment by dotbanana** [comment]
I get the same now. When running normal scenario. It occurs in maybe three out of ten times. When it occurs the whole proxy stalls until i click ok. I used three different versions. The older release, the newer release and lastly i took the actuall master from github and started it with nodejs. Everytime the same. Here a screenshot:  



![unbenannt](https://user-images.githubusercontent.com/22258372/30001235-f9c81c98-9087-11e7-9199-ca39120a17eb.png)
