### ISSUE TITLE
Don't get the .json file on new account

### ISSUE THREAD

**Issue by iuriscotton** [Xzandro/sw-exporter#57]
I got SWEX working on previous accounts normally, but now with the new account I cannot.
I get all logs and no .json File even the app saved profile data.
The account its already with Hive, facebook and google synched.
Using the latest release on Mac.
On others accounts the file appears normally.

Sorry about English, its not my language.
Thanks

**Comment by porksmash** [comment]
Enable the ExamplePlugin in SWEX options and tell us if you see the HubUserLogin command. If not, your account is stored locally on your phone and not on Hive and we cannot extract it. 

![image](https://cloud.githubusercontent.com/assets/11867035/26737558/88596e1e-477f-11e7-9b06-e86a82493b82.png)

**Comment by iuriscotton** [comment]
Yes.
![screen shot 2017-06-02 at 14 45 40](https://cloud.githubusercontent.com/assets/22456182/26737830/35793e0e-47a2-11e7-9cc0-da3ad1ada4b1.png)

**Comment by porksmash** [comment]
What is the content of that file?

**Comment by iuriscotton** [comment]
For me on my Mac says that file is invalid, but he imported it on windows and im using a Mac. 

tomorrow I will try on diferent device.
