### ISSUE TITLE
Problems connecting to Wifi on device using http proxy

### ISSUE THREAD

**Issue by montibeller26** [Xzandro/sw-exporter#58]
My first time trying to do this. I am using v0.0.17 on Mac. Firewall is deactivated.
When I try connecting on my phone (iOS), Wifi does alright UNTIL I enter proxy data (triple-checked correct IP and Port). After this the Wifi connection seems maintained, but I can't load any network features (let alone open the game).
Dont know whether this is relevant or not, but right now I am using a hotel wifi (which has that inconvenient login page). Both my mac and device were properly connected when I began.

**Comment by Xzandro** [comment]
Public Wifi's usually dont allow the communication this way. So that might be the reason for your problem.

**Comment by porksmash** [comment]
I agree this sounds exactly like client isolation. On public or guest wireless networks it is common not to allow devices on the wifi network to talk to each other for security reasons. I'm going to close this but if you end up on a normal home wifi network and still have issues feel free to comment again.
