### ISSUE TITLE
Modify network connection

### ISSUE THREAD

**Issue by Kwarlis** [Xzandro/sw-exporter#59]
Hi, I'm having a problem getting my phone to accept the proxy information. I'm using a Samsung Note 3. I go into the networks Advanced Options, but as soon as i change the proxy from "none" to "manual," the save option greys out.  No matter what information I fill into advanced options, It wont let me save it. Any fix for this?

**Comment by Xzandro** [comment]
This is not a problem with SWEX, it rather is a problem with your phone. We cant really give support for everyone phone out. :/
