### ISSUE TITLE
Error Loggin In

### ISSUE THREAD

**Issue by Mark19861** [Xzandro/sw-exporter#63]
When I set up the proxy and try to log on, I get Hive errors.

**Comment by Xzandro** [comment]
Specific errors would be interesting.

**Comment by starrman03** [comment]
I had the same error at first, but than I realized I put the IP from the "help" section in my settings thinking it was my computer IP. Perhaps this is what happened? I got timed out and the hive error. Once I put the correct IP in, I was able to login.
