### ISSUE TITLE
failed to load the page, please try again later

### ISSUE THREAD

**Issue by skippythewalrus** [Xzandro/sw-exporter#65]
After setting my wifi settings to the one of sw exporter, i launch summoners war and click touch to start. Then, it leads me to this error screen that says Failed to load the page. Please try again later. Retry. On the top right there's back to game and top left it says hive.

**Comment by Xzandro** [comment]
That probably means that you didnt set it up correctly. Make sure that you entered the right information and that no security software is blocking the access.
