### ISSUE TITLE
Error: can't connect to server 

### ISSUE THREAD

**Issue by silent5am** [Xzandro/sw-exporter#67]
I've been using the Portable-0.0.17-win-64.exe successfully for about five weeks, but since the new event started, it will give me an error: can't connect to server when on the SW loading screen.

It seems to be related with the proxy settings because when I remove them from my phone's wireless settings, everything works just fine.

I've tried to log into the game via mobile data, then switched to wireless once I'm inside the game - however in that case the SW exporter doesn't gather any data anymore.

So it seems SW somehow can detect I'm using a proxy and/or something is trying to fetch data and blocks me from logging in. 

Any idea what I can do? Is there a fix on the way?

**Comment by Mark19861** [comment]
Same issue.... any suggestions as to ways around this?

**Comment by Xzandro** [comment]
#70 look here.
