### ISSUE TITLE
won't import .json file

### ISSUE THREAD

**Issue by cgh1215** [Xzandro/sw-exporter#69]
When I connect to the proxy with my phone to generate a .json file and then go to upload and import it to the optimizer, it doesn't do anything. I choose the file, click import, but nothing happens.

**Comment by Xzandro** [comment]
That has nothing to do with SW Exporter. SWOP is a different tool. Make sure, that you use a up-to-date browser. Safari & Internet Explorer is not supported, I recommend Firefox or Chrome.
