### ISSUE TITLE
Cannot Connect to Game Server with Proxy Settings

### ISSUE THREAD

**Issue by LaxerFL** [Xzandro/sw-exporter#70]
After setting up my phone's wi-fi with the proxy settings I cannot connect to the game. The game loads and the Hive Login Page pops up but displays the error, "Can't Connect, Try Again". When I tap "Try Again" it attempts to connect for a few moments and returns a "Timed Out" Error. Since I am unable to enter my login information at this screen, I cannot log into the game.
I have triple checked that all proxy settings are correct and they are. As soon as I remove these proxy settings from my phone's wi-fi, I can enter the game as normal. Not sure what the issue is but I can't use this program and the proxy settings and still connect to the game server.
Any help would be great as this program is highly recommend by my guildmates and I would very much like to use it!
Thanks,
LaxerFL

Edit: Forgot to mention I am using the Portable x64 version on a Windows 10 computer, my phone is running Android 5.1, and I have Comcast XFinity Wi-Fi. If there is any other information that would be helpful, please let me know. Thanks again.

**Comment by Xzandro** [comment]
A security software is blocking the access then. Make sure to set an exception in that software for SW Exporter. There are no other issues I know of.

**Comment by Shinzah** [comment]
Same here, unable to connect when the proxy is used.

**Comment by Xzandro** [comment]
As I stated in many other issues. There is no common 'fix'. In 99% of the cases its one of those issues:

- Entered wrong IP / Port information
- Security software is blocking the access for SW Exporter (most common error)
- You are in a public network (university etc.). The process usually doesnt work in those networks

Other than that, there are no code bugs that I know of. And its seems to work for the majority of people. I will close this ion a few days, unless someone has more information about this issue.

**Comment by LaxerFL** [comment]
When you say Security software is blocking the proxy do you mean on the PC
or on the phone? The only antivirus on my phone does not have a white list
for exceptions...

**Comment by Xzandro** [comment]
On your PC.

**Comment by LaxerFL** [comment]
ok, thanks so much!! It's working perfectly now!! i appreciate the work you
do on this program and your quick replies! keep up the great work!
Lax
