### ISSUE TITLE
json file not created

### ISSUE THREAD

**Issue by charis1701** [Xzandro/sw-exporter#71]
SWEX installs and runs with no error messages (Windows 10)
After starting up Summoners War everything appears to be logging successfully except no rune data json file is created and nothing appears in the log about it.
Dungeons, rune drops all appear in log. Friends' .json files can be created, just not my own,
The old SWProxy creates a .json file with no issues.

I don't know if it makes a difference but I don't have a HIVE login.

Any help would be appreciated. Thanks.

**Comment by Xzandro** [comment]
You need a Hive login. Otherwise the event for your own data is different and it doesnt work for your own file.
