### ISSUE TITLE
swap dont recognize .json

### ISSUE THREAD

**Issue by bhalk** [Xzandro/sw-exporter#73]
hi, i have a problem with swap. I have win 8.1 64 and try both archives to download but when a took the .jason and go to tool.swap.one cant import or export. program said...no data to export and import dont do anything.  I have chrome on date. may you help me ? thanks a lot

**Comment by Xzandro** [comment]
This is probably not an issue with SWOP. Did you open the file and looked at the content? Is the file empty?

**Comment by bhalk** [comment]
I dont know how to do. Some specific program? I downloaded both for win64
but con run de archive. Size 1.08mb

**Comment by Squishie27** [comment]
Hi there, i am having the same issue. see console error log below.
![image](https://user-images.githubusercontent.com/29996200/27983247-37c1a12e-63b8-11e7-93ab-1215f37b041c.png)
and here is the line of code 
![image](https://user-images.githubusercontent.com/29996200/27983254-6e0fb11c-63b8-11e7-9711-3f9aae48355c.png)

i have double checked my file, it does have data.
let me know if you need anything else from me
