### ISSUE TITLE
Javascript exception, port null

### ISSUE THREAD

**Issue by MsgMe** [Xzandro/sw-exporter#74]
AVG antivirus going crazy since i installed the plugging, telling me tons of malware come out of it.

every 30 sec, this image pops
https://prnt.sc/ft6q0j
and i have to ack the exception to unfreeze the app.

**Comment by Xzandro** [comment]
Thats probably an issue with your security software. We dont really support the usage of security software other than the built in ones. I leave it open, maybe othe rpeople can help you.

**Comment by MsgMe** [comment]
Thanks for the fast feedback.
fyi, i disabled AVG and i'm still randomly getting the same error, so it's probably not related to it.

**Comment by DemonSkye** [comment]
@MsgMe -- Did you ever get this figured out?  Adding an exception to windows firewall might help with this issue, especially if you're using a strange port for this.

**Comment by MsgMe** [comment]
i hadn't tried it in a while. I just did download 0.0.19 and it's been working fine for 30 min, but then i started getting some related errors
 https://prnt.sc/gbvs73
which again freeze the the main app. I'm still using the app to export the profile, but that's pretty much all i can reliably do. thanks for asking.

**Comment by Xzandro** [comment]
Do you have any weird network setup or other security software? We use a package called [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) for proxying the requests and there are known issue with the same error. Cant reproduce them myself though. So we probably cant do anything except waiting for a fix from them... or switch to another lib, which takes a little effort.

**Comment by MsgMe** [comment]
I don't feel like i have any weird network setup, and the only security software I'm using is AVG. When i only start the exporter, i get the port exception every few minutes (high variance). Then, when i actually set my iphone to use the proxy, AVG goes crazy about what's being downloaded since it goes through the PC. (https://prnt.sc/gc4sk6 , https://prnt.sc/gc4xit, https://prnt.sc/gc516q) I googled up few of those domain and it seems usual for those domain to be blocked by security software... there's a lot of fishy Chinese stuff in there. I understand this is out of the scope of the exporter thought, still it might be related. Thanks

**Comment by Xzandro** [comment]
To add to this issue. More people with AVG messaged me with this problem. It seems even if you set SW Exporter as an exception AVF does weird things. I recommend to deinstall it and just use Windows Defender and the built in Windows Firewall. Should be enough anyway nowadays.
