### ISSUE TITLE
No .JSON file created on Mac OSX 10.12

### ISSUE THREAD

**Issue by Latexblade** [Xzandro/sw-exporter#75]
I recently installed SW Exporter tool and was able to run it, gather the .JSON file and submit it to SWOP. Then, not necessarily understanding everything, I deleted the .JSON from the folder created on desktop, and since then I have not been able to create another JSON. 

Once I received some sort of NULL error but, I didn't screenshot. 

Any advice?

**Comment by Xzandro** [comment]
Without the error I cant really help you.

**Comment by Latexblade** [comment]
I’ve been able to re-install the SW-exporter and it seems to be working ok. If I have further problems I’ll attempt to screecap and send the details.
