### ISSUE TITLE
Convert file back to EXE

### ISSUE THREAD

**Issue by limahyi** [Xzandro/sw-exporter#76]
I have make some adjustment and would like to test it out.

Which compiler should i use for this case?

**Comment by Xzandro** [comment]
Depends on your OS. There are a few prepared distribute scripts in the package.json.

```
"dist:win64": "build --x64",
"dist:win32": "build --ia32",
"dist:mac": "build",
"dist:linux": "build",
```
so basically:
To refresh the bundled javascript file:
`$ npm webpack`
and to build the exe (as an example)
`$ npm run dist:win64`

You can only build executables for the same platform you are currently using.
