### ISSUE TITLE
import swop not working

### ISSUE THREAD

**Issue by lionheart13** [Xzandro/sw-exporter#77]
can you tell me what I might be doing wrong I have already gotten my json file extracted and when I pull up the optimizer and insert my optimizer.json file and hit import button nothing happens.  is there a setting on my computer I need to change or do I need to leave the proxy connection up the entire time

**Comment by porksmash** [comment]
You are using SWProxy, which is no longer supported or maintained by anyone, and also trying to import the wrong file into SWOP. Download SW-Exporter from the releases of this project and import the one JSON file it exports into SWOP.
