### ISSUE TITLE
Column separator for <accountName>-runs.csv file

### ISSUE THREAD

**Issue by Alex94cerio** [Xzandro/sw-exporter#78]
Hi!
I just want to say that now the column separator for the file <accountName>-runs.csv is ","
But when I open the file in Excel it doesn't recognize all the columns, because by default the column separator for .csv files is ";" (like in the table of all the monsters, there is correct).
Thanks for all the work you have done for this, It's fantastic
I'll donate something as I have some money =)
You really deserve it ;)

**Comment by Xzandro** [comment]
Hi. What do you mean with the table of all monsters? Summoners War Exporter doesnt have a csv files with all monsters. The separator ',' should work fine and is the default deparator in most regions. In some regions its ';'. Either way, in pretty much all programs you can setup the separator. https://superuser.com/questions/606272/how-to-get-excel-to-interpret-the-comma-as-a-default-delimiter-in-csv-files Maybe we could implement a setting for the separator in the future, but it should work fine.

**Comment by Alex94cerio** [comment]
With "the table of all monsters" I mean the file mons-data.csv (downloadable from the website https://tool.swop.one/)
This are the first 3 rows of that file
```
DT_RowId;id;name;level;unit_id;master_id;stars;attribute;location;b_hp;b_atk;b_def;b_spd;b_crate;b_cdmg;b_res;b_acc;b_dps;a_hp;a_atk;a_def;a_spd;a_crate;a_cdmg;a_res;a_acc;a_dps;a_effhp;a_effhp_d;m_hp;m_atk;m_def;m_spd;m_crate;m_cdmg;m_res;m_acc;m_dps;m_effhp;m_effhp_d;o_spd_p;om_spd_p;rune_avg;rune_ids;sets;slots246;rune_max;b_effhp;b_effhp_d;runesLocked
"row_1";1;"Konamiya";40;8107964;10911;6;"Water";"inventory";11700;384;483;91;15;50;15;0;412;11700;384;483;91;15;50;15;0;412;28653;16785;11700;384;483;91;15;50;15;0;412;28653;16785;0;0;0;"";"";"";15;28653;16785;
"row_2";2;"Megan";40;8107971;15911;6;"Water";"inventory";9885;582;571;97;15;50;15;0;625;21451;735;1097;218;23;71;21;60;855;92046;42629;22009;771;1133;218;23;71;21;60;896;96817;44451;0;0;"65.45";"471,472,473,474,475,476";"Swift,Focus";"SPD, HP%, DEF%";15;26818;14964;
```
 While the file -runs.csv is like this
```
date,dungeon,result,time,mana,crystal,energy,drop,grade,sell_value,set,efficiency,slot,rarity,main_stat,prefix_stat,sub1,sub2,sub3,sub4,team1,team2,team3,team4,team5
2017-07-19 01:06,"Giant's Keep B10",Win,1:09,4067,0,1,Rune Piece x9,,,,,,,,,,,,,Lushen,Lushen,Galleon,Akhamamir,Bernard
```

By the way I managed to setting up the separator in Excel , thanks ;)

**Comment by Xzandro** [comment]
Yea, I needed that in SWOP because there are ',' in the data directly, so another separator was needed. btw. this is solely for Summoners War Exporter here :) Glad you found a solution.
