### ISSUE TITLE
Issue pulling JSON

### ISSUE THREAD

**Issue by cedoff** [Xzandro/sw-exporter#82]
I downloaded the program fine and have tried it both my allowing and not allowing through firewall also have tried running as admin, but the issue is when using the program it doesn't allow my SW to run. I have made sure the IP and port are entered properly into manual location on my device (IOS). I have even tried different port numbers, but when I start proxy and start up SW it gets stuck on "Checking for Updates" then give me an error message.

**Comment by Staxed** [comment]
I have this same issue as well.  The only way I can get it to work is turning off windows firewall completely.  I have made inbound rules to allow port 8080 and 56600-56699 on all networks just to check.  Setting these rules removes all the drop messages from the firewall log, but I still get the cannot connect to network issue when launching SW.

What all needs to be done to allow the connection?  I have done the above rules as well as added SWExporter to exemptions, yet still having this issue.

**Comment by Xzandro** [comment]
You need to allow the exe itself and the port you're using. There are no known bugs regarding that matter. I use the Windows Firewall as well and I got a prompt at the very first start of the proxy. I did allow it and since then it just works completely fine.
