### ISSUE TITLE
Compact Mode

### ISSUE THREAD

**Issue by joaokamun** [Xzandro/sw-exporter#83]
I often catch myself opening developers tools and removing topbar and sidebar, to use less space. I don't have much knowledge of electron and stuff, but its possible to made a "compact mode" that only shows the Logs session? 

Anyway, this weekend I'll start look about this. But maybe you guys already know if electron has any limitation regard this.

Example:
![image](https://user-images.githubusercontent.com/7095828/28482856-ca791e6a-6e40-11e7-8f7a-d4d490773f6b.png)

**Comment by Xzandro** [comment]
That should be super easy. Since its CSS you can just use media queries to hide elements for a specific width.

**Comment by joaokamun** [comment]
PR on #84

**Comment by joaokamun** [comment]
Merged on #87
