### ISSUE TITLE
Live Stats feature

### ISSUE THREAD

**Issue by cdmichaelb** [Xzandro/sw-exporter#86]
Some might have to be estimated, I'm not sure  how much is gatherable but: Current Mana, Crystals, Energy, Wings... but most importantly, the "Storage" so like essences and the crystals. Status on buildings even, perhaps. 

I can't tell you how much time I waste switching screens just so I can see what my current count is. :stuck_out_tongue: Well com2us added a count to essences, but there's still nothing for crystal essences (from the elemental raids) but I figure if you're doing a little bit, why not all?

Could have an extra tab or something that has all that info.

Maybe even implement some sort of alert feature. So if you're doing like 10000 fire raid runs, you can get a notification "Hey you have 1000 fire crystals" or "Hey you're over 1million mana"

**Comment by joaokamun** [comment]
I really liked this idea as a plugin. This weekend I'll be kind busy, but next week I give a shot.

**Comment by Xzandro** [comment]
Could be a pain though. The initial build is quite easy and every data needed is in the HubUserLogin event. To update the stats AFTER that you will need to listen to a bunch of events. Wings, RTA Wings, GW Swords, Mana, Crystals, Scrolls and Essences. You can obtain some items in so much events and many events have a different format, tedious. But feel free to do it, I really like the idea.

**Comment by joaokamun** [comment]
Just passing to say, that I stopped working on this for awhile. My current job is consuming much time, I've barely opened SW last two weeks. :(
