### ISSUE TITLE
Javascript error - rift beast

### ISSUE THREAD

**Issue by tkchang9** [Xzandro/sw-exporter#90]
https://i.imgur.com/A7NLY7r.jpg

Error occurs after completing a Fire Beast run. I'm not sure if it's relevant, but the loot was a rare tolerance grindstone.

Exporter continues as normal after dismissing the error window.

**Comment by joaokamun** [comment]
@Xzandro I believe this is a Typo, PR sent on #91 - untested actually.

**Comment by Xzandro** [comment]
Fixed in v0.0.19
