### ISSUE TITLE
Javascript Error - Rift Beast: Summoning stones

### ISSUE THREAD

**Issue by tkchang9** [Xzandro/sw-exporter#93]
https://i.imgur.com/c2eZntr.jpg

Javascript error occurs upon completion of fire beast. Exporter continues as normal after dismissing error. I think this is from the run logger plugin.

Loot from the fire beast was: summoning stones x2, seems to also occur when getting shapeshifting stones as well.

**Comment by Xzandro** [comment]
This is just a quick fix to prevent this error. Summoning Stones are already implemented. I dont know the id for Shapeshifting Stones. There are more items that aren't supported yet, like rune pieces. Tagging @DemonSkye

**Comment by MusashiBR** [comment]
https://imgur.com/a/R5FhQ

I got this error after finishing Wind or Ice beast.

And the loot when this message showed up was Hero Grindstone Accuracy DEF +12~22

**Comment by Xzandro** [comment]
That is not related. You just dont use the newest version.

**Comment by dotbanana** [comment]
I get "Javascript error" also now. When running normal scenario. It occurs in maybe three out of ten times. When it occurs the whole proxy stalls until i click ok. I used three different versions. The older release, the newer release and lastly i took the actuall master from github and started it with nodejs. Everytime the same. Here a screenshot:  



![unbenannt](https://user-images.githubusercontent.com/22258372/30001235-f9c81c98-9087-11e7-9199-ca39120a17eb.png)

**Comment by DemonSkye** [comment]
If you have full run logging enabled can you please upload your log?  This is a known issue -- I have run it about 140 times with no drops on summoning stones, the logic is ready too. 

Thanks,

**Comment by Xzandro** [comment]
Could you try it again from source?

**Comment by Xzandro** [comment]
Released a new version (0.0.20). I will close this for now.
