### ISSUE TITLE
Is there a way to send data from a plugin to a page?

### ISSUE THREAD

**Issue by GuiCavi** [Xzandro/sw-exporter#94]
Hello,

I looked into all plugins available inside '/plugins' and could not find a way to send data from a plugin to a page. All plugins work writing files.

Maybe I'm too new to 'plugins design pattern' and still don't full understand it. Is there any way to do it?

Thanks for now.

- If I said something wrong, please feel free to correct

:smile:

**Comment by Xzandro** [comment]
What do you mean with send data to a page? To a website? There are plugins that send data toa website. swag-logger & swarfarm-logger.

**Comment by GuiCavi** [comment]
For example, at this point (*run-logger.js*):

```js
const headers = ['date', 'dungeon', 'result', 'time', 'mana', 'crystal', 'energy', 'drop', 'grade', 'sell_value', 'set', 'efficiency', 'slot', 'rarity', 'main_stat', 'prefix_stat', 'sub1', 'sub2', 'sub3', 'sub4', 'team1', 'team2', 'team3', 'team4', 'team5'];

const filename = sanitize(`${wizardName}-${wizardID}-runs.csv`);
this.saveToFile(entry, filename, headers, proxy);

//I wanna send 'entry' to a new page I'm creating inside pages folder
```

**Comment by Xzandro** [comment]
Sorry, but I still dont know what you mean by 'page'. You lost me completely on 'inside pages folder'.

**Comment by GuiCavi** [comment]
The view folder, with the react code.

![This folder](https://user-images.githubusercontent.com/7794819/29758568-fc92878a-8b8a-11e7-94b1-b817d7c69753.png)

**Comment by Xzandro** [comment]
So basically you want to access the entry data in the react view? You need to send the data to the renderer process via `window.webContents.send(test, { data })` and listen to it in the renderer process via [ipcRenderer](https://electron.atom.io/docs/api/ipc-renderer/)

Since our main window is available globally you can do `window.webContents.send(test, { data })`.

And in the view:

```Javascript
ipcRenderer.on('test', (event, data) => {

 });
```

**Comment by GuiCavi** [comment]
Thanks, 

> Since our main window is available globally you can do window.webContents.send(test, { data })

this is what I needed to know.

:smile:
