### ISSUE TITLE
Don't jave json file

### ISSUE THREAD

**Issue by BBYNico** [Xzandro/sw-exporter#97]
Hi all,

I have a problem
I have installed SWEX, i have no problem, but i don't have my profil export...
I don't know why, can U help me please ?
![m8xx2endw6uf](https://user-images.githubusercontent.com/31617004/30020665-f2a5f074-9164-11e7-90c0-19b7d9cc8aa3.png)
![smpu5h523xmz](https://user-images.githubusercontent.com/31617004/30020674-f7dbb9de-9164-11e7-8ef8-cd2345c102ed.png)

I have an iPhone 7...

**Comment by Xzandro** [comment]
Is your account conntected to hive? It's mendatory. I fixed that issue in the source, but I havent released a new version yet.

**Comment by BBYNico** [comment]
Thanks for your answer.
I don't have a HIVE account...
When Will be the next release please ?

**Comment by Xzandro** [comment]
I dont really know yet. Within the next days I guess.

**Comment by Xzandro** [comment]
Released a new version 0.0.20. Should work now.
