### ISSUE TITLE
Failed to connect with network. Please Try again later.(7)

### ISSUE THREAD

**Issue by JkLGemma** [Xzandro/sw-exporter#99]
Hello.

First of all, I'm not english native so I'm sorry for my poor english and I hope you will understand me.

I have a random Acer Laptop (W8.1) and an Iphone 4S (iOS 9.3.5).

I have trouble sync-ing SW-exporter with SWar. I did put the good IP and Port adress in the iOS wifi http Proxy (the IP and Port sw-ex give me), but when I launch the game, there is the white screen with "Com2US" and then a black screen, after waiting some seconds, the black screen go out and "Checking for Updates!" appears, and it's where I have the error in the title "Failed to connect with network. Please Try again later.(7)".

I have no firewall on my box, nor on my PC, nor on my Phone, even WDefender is out.

Do you know how to fix it ? I was using SW Proxy for years with no trouble, and then same error, I tried with SW-exporter, same error, im in trouble.

Greetings, Gemma.

**Comment by Xzandro** [comment]
Are you sure that no Firewall is involved? W8.1 has an integrated one and its mandatory to add SWEX as an exception, for private AND public networks. Thats very important, cause some people have their network as public set up.

Other than that, there are no real known issues I know of. Restart your router / phone. Double check the IP & port. Make sure that you only have one IP selectable (you can open the IP select in SWEX). But as I said, its probably just the integrated firewall.

**Comment by JkLGemma** [comment]
I've restart all the house (I've cut the electricity), so the routeur/phone/computer have been restart already. Ip & Port are fine, and only one selectable appear.

The Windows Firewall is OFF in my services.msc (I kinda hate windows involved thing).
I'll try to put him ON and authorize SW-exporter and I'm coming back with some new.

**Comment by Xzandro** [comment]
Alright, cool that its working for you now.
